import type { LibraryDish } from "./global-dish-library";

export const DRINKS_AND_DESSERTS: LibraryDish[] = [
  {
    name: "Lager",
    category: "Beverages",
    cuisines: ["bar","american","global"],
    description: "A crisp, clean, and refreshing lager beer served ice cold.",
    isVegan: true,
    imageUrl: "/images/library/lager.jpg",
  },
  {
    name: "Ale",
    category: "Beverages",
    cuisines: ["bar","british","global"],
    description: "A full-bodied ale with a warm amber color and a complex fruity, malty flavor.",
    isVegan: true,
    imageUrl: "/images/library/ale.jpg",
  },
  {
    name: "Stout",
    category: "Beverages",
    cuisines: ["bar","irish","british"],
    description: "A dark, roasted stout with rich notes of coffee, dark chocolate, and caramel.",
    isVegan: true,
    imageUrl: "/images/library/stout.jpg",
  },
  {
    name: "Porter",
    category: "Beverages",
    cuisines: ["bar","british","global"],
    description: "A robust dark porter with deep malt character and hints of toffee and chocolate.",
    isVegan: true,
    imageUrl: "/images/library/porter.jpg",
  },
  {
    name: "Wheat Beer",
    category: "Beverages",
    cuisines: ["bar","german","global"],
    description: "A hazy, light wheat beer with notes of banana, clove, and citrus.",
    isVegan: true,
    imageUrl: "/images/library/wheat-beer.jpg",
  },
  {
    name: "IPA",
    category: "Beverages",
    cuisines: ["bar","american","global"],
    description: "A bold India Pale Ale bursting with tropical hop aromas, citrus notes, and a dry bitter finish.",
    isVegan: true,
    imageUrl: "/images/library/ipa.jpg",
  },
  {
    name: "Pale Ale",
    category: "Beverages",
    cuisines: ["bar","american","british"],
    description: "A balanced pale ale with a moderate hop presence and a clean, easy-drinking malt backbone.",
    isVegan: true,
    imageUrl: "/images/library/pale-ale.jpg",
  },
  {
    name: "Dark Ale",
    category: "Beverages",
    cuisines: ["bar","british","global"],
    description: "A smooth, dark ale with rich caramel and toasted malt flavors and a gentle bitterness.",
    isVegan: true,
    imageUrl: "/images/library/dark-ale.jpg",
  },
  {
    name: "Sour Beer",
    category: "Beverages",
    cuisines: ["bar","american","belgian"],
    description: "A tart and funky sour beer with bright acidity, complex fruity notes, and a refreshing finish.",
    isVegan: true,
    imageUrl: "/images/library/sour-beer.jpg",
  },
  {
    name: "Merlot",
    category: "Beverages",
    cuisines: ["bar","wine bar","fine dining"],
    description: "A soft, velvety red wine with ripe plum, chocolate, and a smooth, approachable finish.",
    isVegan: true,
    isGlutenFree: true,
    imageUrl: "/images/library/merlot.jpg",
  },
  {
    name: "Pinot Noir",
    category: "Beverages",
    cuisines: ["bar","wine bar","fine dining","french"],
    description: "An elegant, light red wine with delicate red berry aromas, earthy notes, and a silky texture.",
    isVegan: true,
    isGlutenFree: true,
    imageUrl: "/images/library/pinot-noir.jpg",
  },
  {
    name: "Shiraz",
    category: "Beverages",
    cuisines: ["bar","wine bar","fine dining","australian"],
    description: "A rich, powerful red wine with bold dark fruit, pepper spice, and a long, warming finish.",
    isVegan: true,
    isGlutenFree: true,
    imageUrl: "/images/library/shiraz.jpg",
  },
  {
    name: "Malbec",
    category: "Beverages",
    cuisines: ["bar","wine bar","argentinian"],
    description: "A deep, inky Argentinian red wine with ripe blackberry, plum, and velvety tannins.",
    isVegan: true,
    isGlutenFree: true,
    imageUrl: "/images/library/malbec.jpg",
  },
  {
    name: "Zinfandel",
    category: "Beverages",
    cuisines: ["bar","wine bar","american"],
    description: "A spicy, fruit-forward red wine with jammy berry flavors and a bold, rich character.",
    isVegan: true,
    isGlutenFree: true,
    imageUrl: "/images/library/zinfandel.jpg",
  },
  {
    name: "Sauvignon Blanc",
    category: "Beverages",
    cuisines: ["bar","wine bar","fine dining","french"],
    description: "A vibrant, aromatic white wine with zesty citrus, fresh herbs, and a crisp, refreshing acidity.",
    isVegan: true,
    isGlutenFree: true,
    imageUrl: "/images/library/sauvignon-blanc.jpg",
  },
  {
    name: "Riesling",
    category: "Beverages",
    cuisines: ["bar","wine bar","german"],
    description: "An aromatic white wine ranging from bone dry to lusciously sweet, with floral notes and bright acidity.",
    isVegan: true,
    isGlutenFree: true,
    imageUrl: "/images/library/riesling.jpg",
  },
  {
    name: "Pinot Grigio",
    category: "Beverages",
    cuisines: ["bar","wine bar","italian"],
    description: "A light, dry Italian white wine with notes of citrus, peach, and a clean, crisp finish.",
    isVegan: true,
    isGlutenFree: true,
    imageUrl: "/images/library/pinot-grigio.jpg",
  },
  {
    name: "Moscato",
    category: "Beverages",
    cuisines: ["bar","wine bar","italian"],
    description: "A light, sweet white wine with delicate peach, apricot, and floral notes and a low alcohol content.",
    isVegan: true,
    isGlutenFree: true,
    imageUrl: "/images/library/moscato.jpg",
  },
  {
    name: "Champagne",
    category: "Beverages",
    cuisines: ["bar","wine bar","fine dining","french"],
    description: "The world's most celebrated sparkling wine, with fine bubbles, toasty brioche notes, and a crisp finish.",
    isVegan: true,
    isGlutenFree: true,
    imageUrl: "/images/library/champagne.jpg",
  },
  {
    name: "Prosecco",
    category: "Beverages",
    cuisines: ["bar","wine bar","italian"],
    description: "A lively Italian sparkling wine with fruity notes of apple, pear, and white peach, perfect as an aperitivo.",
    isVegan: true,
    isGlutenFree: true,
    imageUrl: "/images/library/prosecco.jpg",
  },
  {
    name: "Cava",
    category: "Beverages",
    cuisines: ["bar","wine bar","spanish"],
    description: "A Spanish sparkling wine made by the traditional method with citrus, almond, and yeasty notes.",
    isVegan: true,
    isGlutenFree: true,
    imageUrl: "/images/library/cava.jpg",
  },
  {
    name: "Rosé Wine",
    category: "Beverages",
    cuisines: ["bar","wine bar","french","mediterranean"],
    description: "A beautiful pale pink wine with delicate notes of strawberry, watermelon, and fresh flowers.",
    isVegan: true,
    isGlutenFree: true,
    imageUrl: "/images/library/rose-wine.jpg",
  },
  {
    name: "Port Wine",
    category: "Beverages",
    cuisines: ["bar","wine bar","portuguese","fine dining"],
    description: "A rich, fortified Portuguese wine with notes of dark fruit, chocolate, and walnut, perfect with dessert.",
    isVegan: true,
    isGlutenFree: true,
    imageUrl: "/images/library/port-wine.jpg",
  },
  {
    name: "Sherry",
    category: "Beverages",
    cuisines: ["bar","wine bar","spanish"],
    description: "A complex, fortified Spanish wine ranging from bone dry and nutty to rich, sweet, and velvety.",
    isVegan: true,
    isGlutenFree: true,
    imageUrl: "/images/library/sherry.jpg",
  },
  {
    name: "Sauternes",
    category: "Beverages",
    cuisines: ["bar","wine bar","fine dining","french"],
    description: "A lusciously sweet French dessert wine with notes of honey, apricot, and noble rot complexity.",
    isVegan: true,
    isGlutenFree: true,
    imageUrl: "/images/library/sauternes.jpg",
  },
  {
    name: "Ice Wine",
    category: "Beverages",
    cuisines: ["bar","wine bar","fine dining","canadian"],
    description: "A rare, intensely sweet dessert wine made from grapes frozen on the vine, with concentrated tropical fruit flavors.",
    isVegan: true,
    isGlutenFree: true,
    imageUrl: "/images/library/ice-wine.jpg",
  },
  {
    name: "Scotch Whiskey",
    category: "Beverages",
    cuisines: ["bar","british","scottish"],
    description: "A smoky, peaty Scottish single malt whiskey with notes of dried fruit, oak, and a long, warming finish.",
    isGlutenFree: true,
    imageUrl: "/images/library/scotch-whiskey.jpg",
  },
  {
    name: "Bourbon Whiskey",
    category: "Beverages",
    cuisines: ["bar","american"],
    description: "An American whiskey aged in charred oak barrels with rich flavors of vanilla, caramel, and toasted oak.",
    isGlutenFree: true,
    imageUrl: "/images/library/bourbon-whiskey.jpg",
  },
  {
    name: "Irish Whiskey",
    category: "Beverages",
    cuisines: ["bar","irish"],
    description: "A smooth, triple-distilled Irish whiskey with light floral notes, honey sweetness, and a gentle spice.",
    isGlutenFree: true,
    imageUrl: "/images/library/irish-whiskey.jpg",
  },
  {
    name: "Japanese Whiskey",
    category: "Beverages",
    cuisines: ["bar","japanese"],
    description: "An elegantly balanced Japanese whiskey with delicate floral notes, subtle fruit, and exceptional smoothness.",
    isGlutenFree: true,
    imageUrl: "/images/library/japanese-whiskey.jpg",
  },
  {
    name: "Rye Whiskey",
    category: "Beverages",
    cuisines: ["bar","american","canadian"],
    description: "A spicy, bold rye whiskey with notes of pepper, dried fruit, and a full-bodied, complex character.",
    isGlutenFree: true,
    imageUrl: "/images/library/rye-whiskey.jpg",
  },
  {
    name: "Vodka",
    category: "Beverages",
    cuisines: ["bar","russian","eastern european","global"],
    description: "A crisp, clean, and neutral spirit distilled to perfection, smooth and versatile.",
    isVegan: true,
    isGlutenFree: true,
    imageUrl: "/images/library/vodka.jpg",
  },
  {
    name: "White Rum",
    category: "Beverages",
    cuisines: ["bar","caribbean","global"],
    description: "A light, clean Caribbean rum with subtle sweetness, perfect for mixing in classic tropical cocktails.",
    isVegan: true,
    isGlutenFree: true,
    imageUrl: "/images/library/white-rum.jpg",
  },
  {
    name: "Dark Rum",
    category: "Beverages",
    cuisines: ["bar","caribbean","global"],
    description: "A rich, aged Caribbean rum with deep molasses, caramel, and spice notes, perfect sipped or mixed.",
    isVegan: true,
    isGlutenFree: true,
    imageUrl: "/images/library/dark-rum.jpg",
  },
  {
    name: "Spiced Rum",
    category: "Beverages",
    cuisines: ["bar","caribbean","global"],
    description: "A warm, aromatic rum infused with exotic spices like cinnamon, nutmeg, and vanilla.",
    isVegan: true,
    isGlutenFree: true,
    imageUrl: "/images/library/spiced-rum.jpg",
  },
  {
    name: "Aged Rum",
    category: "Beverages",
    cuisines: ["bar","caribbean","latin american"],
    description: "A premium rum aged in oak barrels, developing extraordinary complexity and a smooth sipping character.",
    isVegan: true,
    isGlutenFree: true,
    imageUrl: "/images/library/aged-rum.jpg",
  },
  {
    name: "Gin",
    category: "Beverages",
    cuisines: ["bar","british","global"],
    description: "A botanical spirit with a distinctive juniper-forward profile layered with citrus, herbs, and floral notes.",
    isVegan: true,
    isGlutenFree: true,
    imageUrl: "/images/library/gin.jpg",
  },
  {
    name: "Tequila Blanco",
    category: "Beverages",
    cuisines: ["bar","mexican","global"],
    description: "A pure, unaged tequila with bright agave flavor, citrus notes, and a crisp, clean finish.",
    isVegan: true,
    isGlutenFree: true,
    imageUrl: "/images/library/tequila-blanco.jpg",
  },
  {
    name: "Tequila Reposado",
    category: "Beverages",
    cuisines: ["bar","mexican","global"],
    description: "A rested tequila aged in oak barrels for 2 to 12 months, gaining soft vanilla and caramel notes.",
    isVegan: true,
    isGlutenFree: true,
    imageUrl: "/images/library/tequila-reposado.jpg",
  },
  {
    name: "Tequila Añejo",
    category: "Beverages",
    cuisines: ["bar","mexican","fine dining"],
    description: "A premium, aged tequila with rich oak, dark fruit, and a smooth, complex sipping character.",
    isVegan: true,
    isGlutenFree: true,
    imageUrl: "/images/library/tequila-anejo.jpg",
  },
  {
    name: "Brandy",
    category: "Beverages",
    cuisines: ["bar","european","global"],
    description: "A smooth, grape-distilled spirit with rich notes of dried fruit, vanilla, and warm oak.",
    isVegan: true,
    isGlutenFree: true,
    imageUrl: "/images/library/brandy.jpg",
  },
  {
    name: "Cognac",
    category: "Beverages",
    cuisines: ["bar","french","fine dining"],
    description: "A prestigious French aged brandy with elegant notes of dried apricot, oak spice, and floral honey.",
    isVegan: true,
    isGlutenFree: true,
    imageUrl: "/images/library/cognac.jpg",
  },
  {
    name: "Baileys Irish Cream",
    category: "Beverages",
    cuisines: ["bar","irish","global"],
    description: "A luscious blend of Irish whiskey, cream, and chocolate, perfectly balanced between sweet and spirit.",
    imageUrl: "/images/library/baileys-irish-cream.jpg",
  },
  {
    name: "Kahlua",
    category: "Beverages",
    cuisines: ["bar","mexican","global"],
    description: "A rich, coffee-flavored Mexican liqueur with deep espresso and dark rum character.",
    isVegan: true,
    imageUrl: "/images/library/kahlua.jpg",
  },
  {
    name: "Amaretto",
    category: "Beverages",
    cuisines: ["bar","italian","global"],
    description: "A sweet Italian almond liqueur with a warm, marzipan flavor and a smooth, velvety finish.",
    isVegan: true,
    imageUrl: "/images/library/amaretto.jpg",
  },
  {
    name: "Cointreau",
    category: "Beverages",
    cuisines: ["bar","french","global"],
    description: "A premium French triple sec liqueur with a perfect balance of sweet and bitter orange flavors.",
    isVegan: true,
    isGlutenFree: true,
    imageUrl: "/images/library/cointreau.jpg",
  },
  {
    name: "Grand Marnier",
    category: "Beverages",
    cuisines: ["bar","french","global"],
    description: "An iconic French liqueur blending fine Cognac with bitter orange essence for a sophisticated, complex flavor.",
    isVegan: true,
    isGlutenFree: true,
    imageUrl: "/images/library/grand-marnier.jpg",
  },
  {
    name: "Sambuca",
    category: "Beverages",
    cuisines: ["bar","italian","global"],
    description: "A powerful Italian anise liqueur traditionally served with three coffee beans floating on top.",
    isVegan: true,
    imageUrl: "/images/library/sambuca.jpg",
  },
  {
    name: "Midori",
    category: "Beverages",
    cuisines: ["bar","japanese","global"],
    description: "A vibrant, emerald-green Japanese melon liqueur with a sweet, fruity flavor and a bright color.",
    isVegan: true,
    imageUrl: "/images/library/midori.jpg",
  },
  {
    name: "Frangelico",
    category: "Beverages",
    cuisines: ["bar","italian","global"],
    description: "A golden Italian hazelnut liqueur with notes of roasted nuts, chocolate, and vanilla.",
    isVegan: true,
    imageUrl: "/images/library/frangelico.jpg",
  },
  {
    name: "Triple Sec",
    category: "Beverages",
    cuisines: ["bar","global"],
    description: "A clear, orange-flavored liqueur that forms the backbone of many classic cocktails.",
    isVegan: true,
    imageUrl: "/images/library/triple-sec.jpg",
  },
  {
    name: "Martini",
    category: "Cocktails",
    cuisines: ["bar","american","global"],
    description: "The king of cocktails — a clean, elegant blend of gin and dry vermouth, served ice cold with an olive.",
    isVegan: true,
    isGlutenFree: true,
    imageUrl: "/images/library/martini.jpg",
  },
  {
    name: "Manhattan",
    category: "Cocktails",
    cuisines: ["bar","american"],
    description: "A sophisticated blend of rye whiskey, sweet vermouth, and Angostura bitters, served with a cherry.",
    isGlutenFree: true,
    imageUrl: "/images/library/manhattan.jpg",
  },
  {
    name: "Negroni",
    category: "Cocktails",
    cuisines: ["bar","italian","global"],
    description: "A perfectly balanced Italian aperitivo of gin, sweet vermouth, and Campari, stirred and served over ice.",
    isVegan: true,
    isGlutenFree: true,
    imageUrl: "/images/library/negroni.jpg",
  },
  {
    name: "Daiquiri",
    category: "Cocktails",
    cuisines: ["bar","cuban","caribbean"],
    description: "A Cuban staple — white rum shaken with fresh lime juice and a touch of sugar for a perfectly tart cocktail.",
    isVegan: true,
    isGlutenFree: true,
    imageUrl: "/images/library/daiquiri.jpg",
  },
  {
    name: "Cosmopolitan",
    category: "Cocktails",
    cuisines: ["bar","american"],
    description: "A glamorous pink cocktail of vodka, triple sec, cranberry juice, and fresh lime juice.",
    isVegan: true,
    isGlutenFree: true,
    imageUrl: "/images/library/cosmopolitan.jpg",
  },
  {
    name: "Sidecar",
    category: "Cocktails",
    cuisines: ["bar","french","american"],
    description: "A Prohibition-era classic of Cognac, Cointreau, and fresh lemon juice with a sugared rim.",
    isVegan: true,
    isGlutenFree: true,
    imageUrl: "/images/library/sidecar.jpg",
  },
  {
    name: "Tom Collins",
    category: "Cocktails",
    cuisines: ["bar","british","american"],
    description: "A tall, refreshing gin cocktail shaken with lemon juice and sugar, topped with soda water.",
    isVegan: true,
    isGlutenFree: true,
    imageUrl: "/images/library/tom-collins.jpg",
  },
  {
    name: "Gimlet",
    category: "Cocktails",
    cuisines: ["bar","british","american"],
    description: "A retro British navy cocktail of gin and lime cordial, clean, tart, and refreshing.",
    isVegan: true,
    isGlutenFree: true,
    imageUrl: "/images/library/gimlet.jpg",
  },
  {
    name: "Moscow Mule",
    category: "Cocktails",
    cuisines: ["bar","american","russian"],
    description: "A zesty vodka cocktail served in a copper mug with ginger beer and fresh lime juice.",
    isVegan: true,
    isGlutenFree: true,
    imageUrl: "/images/library/moscow-mule.jpg",
  },
  {
    name: "Dark and Stormy",
    category: "Cocktails",
    cuisines: ["bar","caribbean","bermudian"],
    description: "A bold, tropical cocktail of dark rum and spicy ginger beer, served over ice with a lime wedge.",
    isVegan: true,
    isGlutenFree: true,
    imageUrl: "/images/library/dark-and-stormy.jpg",
  },
  {
    name: "Long Island Iced Tea",
    category: "Cocktails",
    cuisines: ["bar","american"],
    description: "A legendary, deceptively strong cocktail combining vodka, tequila, rum, gin, triple sec, and a splash of cola.",
    isVegan: true,
    isGlutenFree: true,
    imageUrl: "/images/library/long-island-iced-tea.jpg",
  },
  {
    name: "Pina Colada",
    category: "Cocktails",
    cuisines: ["bar","puerto rican","caribbean"],
    description: "A tropical paradise in a glass — blended white rum, coconut cream, and pineapple juice.",
    isVegan: true,
    isGlutenFree: true,
    imageUrl: "/images/library/pina-colada.jpg",
  },
  {
    name: "Tequila Sunrise",
    category: "Cocktails",
    cuisines: ["bar","mexican","american"],
    description: "A visually stunning gradient cocktail of tequila, orange juice, and grenadine mimicking a sunrise.",
    isVegan: true,
    isGlutenFree: true,
    imageUrl: "/images/library/tequila-sunrise.jpg",
  },
  {
    name: "Whiskey Sour",
    category: "Cocktails",
    cuisines: ["bar","american"],
    description: "A classic bourbon cocktail shaken with fresh lemon juice and simple syrup, topped with an egg white foam.",
    isGlutenFree: true,
    imageUrl: "/images/library/whiskey-sour.jpg",
  },
  {
    name: "Boulevardier",
    category: "Cocktails",
    cuisines: ["bar","american","french"],
    description: "A Negroni's sophisticated cousin — bourbon, sweet vermouth, and Campari, stirred to perfection.",
    isGlutenFree: true,
    imageUrl: "/images/library/boulevardier.jpg",
  },
  {
    name: "Frozen Margarita",
    category: "Cocktails",
    cuisines: ["bar","mexican","tex-mex"],
    description: "A slushy, blended margarita — the ultimate hot-weather refreshment.",
    isVegan: true,
    isGlutenFree: true,
    imageUrl: "/images/library/frozen-margarita.jpg",
  },
  {
    name: "Strawberry Margarita",
    category: "Cocktails",
    cuisines: ["bar","mexican","tex-mex"],
    description: "Fresh strawberries blended with tequila and lime for a vibrant twist on the classic.",
    isVegan: true,
    isGlutenFree: true,
    imageUrl: "/images/library/strawberry-margarita.jpg",
  },
  {
    name: "Mango Margarita",
    category: "Cocktails",
    cuisines: ["bar","mexican","tex-mex"],
    description: "A tropical margarita with sweet mango puree, tequila, lime, and a Tajín-dusted rim.",
    isVegan: true,
    isGlutenFree: true,
    imageUrl: "/images/library/mango-margarita.jpg",
  },
  {
    name: "Watermelon Margarita",
    category: "Cocktails",
    cuisines: ["bar","mexican","tex-mex"],
    description: "A refreshing summer margarita made with fresh watermelon juice, tequila, and a squeeze of lime.",
    isVegan: true,
    isGlutenFree: true,
    imageUrl: "/images/library/watermelon-margarita.jpg",
  },
  {
    name: "Coconut Margarita",
    category: "Cocktails",
    cuisines: ["bar","mexican","caribbean"],
    description: "A tropical take on the classic, blending tequila with creamy coconut milk and fresh lime.",
    isVegan: true,
    isGlutenFree: true,
    imageUrl: "/images/library/coconut-margarita.jpg",
  },
  {
    name: "Blueberry Margarita",
    category: "Cocktails",
    cuisines: ["bar","mexican","american"],
    description: "A deep purple margarita made with muddled fresh blueberries, tequila, and a bright citrus accent.",
    isVegan: true,
    isGlutenFree: true,
    imageUrl: "/images/library/blueberry-margarita.jpg",
  },
  {
    name: "Peach Margarita",
    category: "Cocktails",
    cuisines: ["bar","mexican","american"],
    description: "A lush, summer margarita made with ripe peach puree and a splash of peach schnapps.",
    isVegan: true,
    isGlutenFree: true,
    imageUrl: "/images/library/peach-margarita.jpg",
  },
  {
    name: "Blue Margarita",
    category: "Cocktails",
    cuisines: ["bar","mexican","global"],
    description: "A stunning electric-blue margarita with tequila, blue curaçao, and fresh lime juice.",
    isVegan: true,
    isGlutenFree: true,
    imageUrl: "/images/library/blue-margarita.jpg",
  },
  {
    name: "Skinny Margarita",
    category: "Cocktails",
    cuisines: ["bar","mexican","american"],
    description: "A light, guilt-free margarita made with just tequila, fresh lime juice, and agave nectar.",
    isVegan: true,
    isGlutenFree: true,
    imageUrl: "/images/library/skinny-margarita.jpg",
  },
  {
    name: "Pomegranate Margarita",
    category: "Cocktails",
    cuisines: ["bar","mexican","middle eastern"],
    description: "A jewel-toned margarita with tart pomegranate juice, tequila, and fresh lime over a salted rim.",
    isVegan: true,
    isGlutenFree: true,
    imageUrl: "/images/library/pomegranate-margarita.jpg",
  },
  {
    name: "Blood Orange Margarita",
    category: "Cocktails",
    cuisines: ["bar","mexican","italian"],
    description: "A gorgeous crimson margarita made with fresh blood orange juice and a smoky mezcal base.",
    isVegan: true,
    isGlutenFree: true,
    imageUrl: "/images/library/blood-orange-margarita.jpg",
  },
  {
    name: "Cucumber Mint Margarita",
    category: "Cocktails",
    cuisines: ["bar","mexican","global"],
    description: "A cool, garden-fresh margarita with muddled cucumber, fresh mint, and a herbaceous tequila finish.",
    isVegan: true,
    isGlutenFree: true,
    imageUrl: "/images/library/cucumber-mint-margarita.jpg",
  },
  {
    name: "Passion Fruit Margarita",
    category: "Cocktails",
    cuisines: ["bar","mexican","tropical"],
    description: "An exotic, tropical margarita with vibrant passion fruit puree balanced by tequila and fresh lime.",
    isVegan: true,
    isGlutenFree: true,
    imageUrl: "/images/library/passion-fruit-margarita.jpg",
  },
  {
    name: "Tommy's Margarita",
    category: "Cocktails",
    cuisines: ["bar","mexican","california"],
    description: "The purist's margarita — 100% agave tequila, fresh lime juice, and agave nectar. Simple and legendary.",
    isVegan: true,
    isGlutenFree: true,
    imageUrl: "/images/library/tommys-margarita.jpg",
  },
  {
    name: "Michelada Margarita",
    category: "Cocktails",
    cuisines: ["bar","mexican"],
    description: "A bold fusion of michelada and margarita — tequila, beer, lime juice, and a spicy Tajín rim.",
    isVegan: true,
    imageUrl: "/images/library/michelada-margarita.jpg",
  },
  {
    name: "Coca-Cola",
    category: "Beverages",
    cuisines: ["bar","american","global"],
    description: "The world's most iconic carbonated cola with its unmistakable sweet, caramel-and-spice flavor.",
    isVegan: true,
    isGlutenFree: true,
    imageUrl: "/images/library/coca-cola.jpg",
  },
  {
    name: "Diet Coke",
    category: "Beverages",
    cuisines: ["bar","american","global"],
    description: "A zero-calorie carbonated cola with the refreshing taste of Coca-Cola without the sugar.",
    isVegan: true,
    isGlutenFree: true,
    imageUrl: "/images/library/diet-coke.jpg",
  },
  {
    name: "Pepsi",
    category: "Beverages",
    cuisines: ["bar","american","global"],
    description: "A bold, slightly sweeter cola with a light, crisp carbonation and a refreshing finish.",
    isVegan: true,
    isGlutenFree: true,
    imageUrl: "/images/library/pepsi.jpg",
  },
  {
    name: "Sprite",
    category: "Beverages",
    cuisines: ["bar","american","global"],
    description: "A lemon-lime carbonated soda with a clean, crisp, and refreshing citrus flavor.",
    isVegan: true,
    isGlutenFree: true,
    imageUrl: "/images/library/sprite.jpg",
  },
  {
    name: "7UP",
    category: "Beverages",
    cuisines: ["bar","american","global"],
    description: "A sparkling lemon-lime soda known for its crisp taste and smooth, refreshing bubbles.",
    isVegan: true,
    isGlutenFree: true,
    imageUrl: "/images/library/7up.jpg",
  },
  {
    name: "Dr Pepper",
    category: "Beverages",
    cuisines: ["bar","american"],
    description: "A unique blend of 23 flavors creating a distinctively sweet, fruity, and spicy carbonated soft drink.",
    isVegan: true,
    isGlutenFree: true,
    imageUrl: "/images/library/dr-pepper.jpg",
  },
  {
    name: "Fanta Orange",
    category: "Beverages",
    cuisines: ["bar","american","global"],
    description: "A vibrant, bubbly orange soda with a sweet, fruity flavor that's bold and fun.",
    isVegan: true,
    isGlutenFree: true,
    imageUrl: "/images/library/fanta-orange.jpg",
  },
  {
    name: "Ginger Ale",
    category: "Beverages",
    cuisines: ["bar","global"],
    description: "A light, refreshing carbonated soda with a delicate ginger flavor, perfect as a mixer or on its own.",
    isVegan: true,
    isGlutenFree: true,
    imageUrl: "/images/library/ginger-ale.jpg",
  },
  {
    name: "Club Soda",
    category: "Beverages",
    cuisines: ["bar","global"],
    description: "A crisp, unflavored carbonated water, perfect for mixing cocktails or enjoying on its own.",
    isVegan: true,
    isGlutenFree: true,
    imageUrl: "/images/library/club-soda.jpg",
  },
  {
    name: "Tonic Water",
    category: "Beverages",
    cuisines: ["bar","british","global"],
    description: "A sparkling water with a distinctive bitter quinine flavor, the essential companion to gin.",
    isVegan: true,
    isGlutenFree: true,
    imageUrl: "/images/library/tonic-water.jpg",
  },
  {
    name: "Root Beer",
    category: "Beverages",
    cuisines: ["bar","american"],
    description: "A classic American soda with a sweet, herbal flavor and creamy vanilla finish.",
    isVegan: true,
    isGlutenFree: true,
    imageUrl: "/images/library/root-beer.jpg",
  },
  {
    name: "Cream Soda",
    category: "Beverages",
    cuisines: ["bar","american","global"],
    description: "A sweet, smooth, vanilla-flavored carbonated soda with a rich, creamy character.",
    isVegan: true,
    isGlutenFree: true,
    imageUrl: "/images/library/cream-soda.jpg",
  },
  {
    name: "Orange Juice",
    category: "Beverages",
    cuisines: ["cafe","american","global"],
    description: "Freshly squeezed orange juice, bursting with natural vitamin C and bright citrus flavor.",
    isVegan: true,
    isGlutenFree: true,
    imageUrl: "/images/library/orange-juice.jpg",
  },
  {
    name: "Apple Juice",
    category: "Beverages",
    cuisines: ["cafe","american","global"],
    description: "Cold-pressed apple juice with a pure, naturally sweet, and refreshing apple flavor.",
    isVegan: true,
    isGlutenFree: true,
    imageUrl: "/images/library/apple-juice.jpg",
  },
  {
    name: "Cranberry Juice",
    category: "Beverages",
    cuisines: ["cafe","american","global"],
    description: "A tart and vibrant cranberry juice with a beautiful deep ruby color and a refreshing zing.",
    isVegan: true,
    isGlutenFree: true,
    imageUrl: "/images/library/cranberry-juice.jpg",
  },
  {
    name: "Pineapple Juice",
    category: "Beverages",
    cuisines: ["cafe","tropical","caribbean"],
    description: "A sweet and tangy pineapple juice with a tropical aroma and naturally bright, golden color.",
    isVegan: true,
    isGlutenFree: true,
    imageUrl: "/images/library/pineapple-juice.jpg",
  },
  {
    name: "Mango Juice",
    category: "Beverages",
    cuisines: ["cafe","indian","tropical"],
    description: "A thick, velvety mango juice with a lusciously sweet tropical flavor.",
    isVegan: true,
    isGlutenFree: true,
    imageUrl: "/images/library/mango-juice.jpg",
  },
  {
    name: "Pomegranate Juice",
    category: "Beverages",
    cuisines: ["cafe","middle eastern","global"],
    description: "A deep ruby pomegranate juice packed with antioxidants and a bold, tart-sweet flavor.",
    isVegan: true,
    isGlutenFree: true,
    imageUrl: "/images/library/pomegranate-juice.jpg",
  },
  {
    name: "Lychee Juice",
    category: "Beverages",
    cuisines: ["cafe","chinese","asian"],
    description: "A delicate, floral lychee juice with a sweet, exotic aroma and a light, refreshing taste.",
    isVegan: true,
    isGlutenFree: true,
    imageUrl: "/images/library/lychee-juice.jpg",
  },
  {
    name: "Passion Fruit Juice",
    category: "Beverages",
    cuisines: ["cafe","tropical","latin american"],
    description: "A vibrant, intensely aromatic passion fruit juice with a tropical sweet-tart balance.",
    isVegan: true,
    isGlutenFree: true,
    imageUrl: "/images/library/passion-fruit-juice.jpg",
  },
  {
    name: "Grapefruit Juice",
    category: "Beverages",
    cuisines: ["cafe","american","global"],
    description: "Freshly squeezed grapefruit juice with a bright, bittersweet citrus flavor and a beautiful blush color.",
    isVegan: true,
    isGlutenFree: true,
    imageUrl: "/images/library/grapefruit-juice.jpg",
  },
  {
    name: "Tomato Juice",
    category: "Beverages",
    cuisines: ["cafe","american","global"],
    description: "A savory, rich tomato juice seasoned with a touch of salt, perfect on its own or as a cocktail base.",
    isVegan: true,
    isGlutenFree: true,
    imageUrl: "/images/library/tomato-juice.jpg",
  },
  {
    name: "Cappuccino",
    category: "Beverages",
    cuisines: ["cafe","italian","global"],
    description: "A classic Italian espresso drink with equal parts espresso, steamed milk, and a thick, velvety foam.",
    isGlutenFree: true,
    imageUrl: "/images/library/cappuccino.jpg",
  },
  {
    name: "Green Tea",
    category: "Beverages",
    cuisines: ["cafe","japanese","chinese","asian"],
    description: "A delicate, antioxidant-rich green tea with a clean, grassy flavor and a gentle, calming character.",
    isVegan: true,
    isGlutenFree: true,
    imageUrl: "/images/library/green-tea.jpg",
  },
  {
    name: "Herbal Tea",
    category: "Beverages",
    cuisines: ["cafe","global"],
    description: "A soothing, caffeine-free blend of dried herbs, flowers, and botanicals steeped in hot water.",
    isVegan: true,
    isGlutenFree: true,
    imageUrl: "/images/library/herbal-tea.jpg",
  },
  {
    name: "Matcha Latte",
    category: "Beverages",
    cuisines: ["cafe","japanese","global"],
    description: "A vibrant, earthy matcha latte made with ceremonial-grade matcha powder and steamed oat or whole milk.",
    isGlutenFree: true,
    imageUrl: "/images/library/matcha-latte.jpg",
  },
  {
    name: "Lemonade",
    category: "Beverages",
    cuisines: ["cafe","american","global"],
    description: "Homemade lemonade with freshly squeezed lemons, pure cane sugar, and chilled sparkling water.",
    isVegan: true,
    isGlutenFree: true,
    imageUrl: "/images/library/lemonade.jpg",
  },
  {
    name: "Arnold Palmer",
    category: "Beverages",
    cuisines: ["cafe","american"],
    description: "The legendary half-and-half of fresh iced tea and lemonade — the perfect all-day refreshment.",
    isVegan: true,
    isGlutenFree: true,
    imageUrl: "/images/library/arnold-palmer.jpg",
  },
  {
    name: "Agua Fresca",
    category: "Beverages",
    cuisines: ["cafe","mexican","latin american"],
    description: "A light, sweet Mexican fruit water made with fresh seasonal fruits, lime juice, and a touch of sugar.",
    isVegan: true,
    isGlutenFree: true,
    imageUrl: "/images/library/agua-fresca.jpg",
  },
  {
    name: "Virgin Mojito",
    category: "Beverages",
    cuisines: ["bar","cuban","global"],
    description: "A refreshing non-alcoholic mojito with fresh mint, lime juice, sugar syrup, and soda water.",
    isVegan: true,
    isGlutenFree: true,
    imageUrl: "/images/library/virgin-mojito.jpg",
  },
  {
    name: "Shirley Temple",
    category: "Beverages",
    cuisines: ["bar","american"],
    description: "A classic non-alcoholic mocktail of ginger ale, orange juice, and a splash of grenadine.",
    isVegan: true,
    isGlutenFree: true,
    imageUrl: "/images/library/shirley-temple.jpg",
  },
  {
    name: "Mango Lassi",
    category: "Beverages",
    cuisines: ["cafe","indian"],
    description: "A beloved Indian yogurt-based drink blended with ripe mangoes, cardamom, and a touch of sugar.",
    isVegetarian: true,
    isGlutenFree: true,
    imageUrl: "/images/library/mango-lassi.jpg",
  },
  {
    name: "Kombucha",
    category: "Beverages",
    cuisines: ["cafe","global","american"],
    description: "A lightly effervescent, fermented tea with a pleasantly tangy, probiotic-rich flavor.",
    isVegan: true,
    isGlutenFree: true,
    imageUrl: "/images/library/kombucha.jpg",
  },
  {
    name: "Sparkling Water",
    category: "Beverages",
    cuisines: ["bar","global"],
    description: "Premium sparkling mineral water with fine carbonation, served chilled with a wedge of lemon.",
    isVegan: true,
    isGlutenFree: true,
    imageUrl: "/images/library/sparkling-water.jpg",
  },
  {
    name: "Coconut Water",
    category: "Beverages",
    cuisines: ["cafe","tropical","asian"],
    description: "Pure, natural coconut water — hydrating, sweet, and naturally electrolyte-rich.",
    isVegan: true,
    isGlutenFree: true,
    imageUrl: "/images/library/coconut-water.jpg",
  },
  {
    name: "Vanilla Milkshake",
    category: "Beverages",
    cuisines: ["cafe","american","diner"],
    description: "A thick, creamy milkshake blended with premium vanilla ice cream and whole milk, topped with whipped cream.",
    isVegetarian: true,
    isGlutenFree: true,
    imageUrl: "/images/library/vanilla-milkshake.jpg",
  },
  {
    name: "Chocolate Milkshake",
    category: "Beverages",
    cuisines: ["cafe","american","diner"],
    description: "A rich, indulgent chocolate milkshake blended with dark chocolate ice cream and topped with whipped cream.",
    isVegetarian: true,
    isGlutenFree: true,
    imageUrl: "/images/library/chocolate-milkshake.jpg",
  },
  {
    name: "Strawberry Milkshake",
    category: "Beverages",
    cuisines: ["cafe","american","diner"],
    description: "A sweet, vibrant milkshake blended with fresh strawberry ice cream and a dollop of whipped cream.",
    isVegetarian: true,
    isGlutenFree: true,
    imageUrl: "/images/library/strawberry-milkshake.jpg",
  },
  {
    name: "New York Cheesecake",
    category: "Desserts",
    cuisines: ["american","diner","cafe"],
    description: "The iconic dense, creamy cheesecake on a buttery graham cracker crust, with a bright berry compote.",
    isVegetarian: true,
    imageUrl: "/images/library/new-york-cheesecake.jpg",
  },
  {
    name: "Brownie",
    category: "Desserts",
    cuisines: ["american","cafe","bakery"],
    description: "A fudgy, dense chocolate brownie with a crackly top, served warm with a scoop of vanilla ice cream.",
    isVegetarian: true,
    imageUrl: "/images/library/brownie.jpg",
  },
  {
    name: "Banana Pudding",
    category: "Desserts",
    cuisines: ["american","southern"],
    description: "Layers of vanilla wafers, fresh banana slices, and creamy vanilla pudding topped with fluffy whipped cream.",
    isVegetarian: true,
    imageUrl: "/images/library/banana-pudding.jpg",
  },
  {
    name: "Key Lime Pie",
    category: "Desserts",
    cuisines: ["american","southern","florida"],
    description: "A tangy, creamy Key lime custard in a buttery graham cracker crust, topped with whipped cream.",
    isVegetarian: true,
    imageUrl: "/images/library/key-lime-pie.jpg",
  },
  {
    name: "Apple Pie",
    category: "Desserts",
    cuisines: ["american","diner","bakery"],
    description: "Classic American apple pie with a flaky, golden crust and a warm, spiced apple filling, best served à la mode.",
    isVegetarian: true,
    imageUrl: "/images/library/apple-pie.jpg",
  },
  {
    name: "Red Velvet Cake",
    category: "Desserts",
    cuisines: ["american","southern","bakery"],
    description: "A dramatic, deep red layered cake with a mild cocoa flavor and a lush cream cheese frosting.",
    isVegetarian: true,
    imageUrl: "/images/library/red-velvet-cake.jpg",
  },
  {
    name: "Peach Cobbler",
    category: "Desserts",
    cuisines: ["american","southern"],
    description: "Juicy Southern peaches baked under a golden, buttery biscuit topping, served warm with vanilla ice cream.",
    isVegetarian: true,
    imageUrl: "/images/library/peach-cobbler.jpg",
  },
  {
    name: "Beignets",
    category: "Desserts",
    cuisines: ["american","southern","french","cajun"],
    description: "New Orleans-style square doughnuts, fried golden and dusted generously with powdered sugar.",
    isVegetarian: true,
    imageUrl: "/images/library/beignets.jpg",
  },
  {
    name: "S'mores",
    category: "Desserts",
    cuisines: ["american","campfire"],
    description: "A campfire classic — toasted marshmallows and melted chocolate sandwiched between graham crackers.",
    isVegetarian: true,
    imageUrl: "/images/library/smores.jpg",
  },
  {
    name: "Crème Brûlée",
    category: "Desserts",
    cuisines: ["french","fine dining"],
    description: "A luxurious vanilla custard with a perfectly caramelized, crackling sugar crust — a French bistro icon.",
    isVegetarian: true,
    isGlutenFree: true,
    imageUrl: "/images/library/creme-brulee.jpg",
  },
  {
    name: "Macarons",
    category: "Desserts",
    cuisines: ["french","bakery","cafe"],
    description: "Delicate, jewel-colored French almond meringue cookies with a smooth ganache or buttercream filling.",
    isVegetarian: true,
    isGlutenFree: true,
    imageUrl: "/images/library/macarons.jpg",
  },
  {
    name: "Profiteroles",
    category: "Desserts",
    cuisines: ["french","fine dining","bakery"],
    description: "Light, airy choux pastry puffs filled with vanilla ice cream and drizzled with warm dark chocolate sauce.",
    isVegetarian: true,
    imageUrl: "/images/library/profiteroles.jpg",
  },
  {
    name: "Mille-Feuille",
    category: "Desserts",
    cuisines: ["french","fine dining","bakery"],
    description: "Hundreds of flaky puff pastry layers sandwiched with silky vanilla cream and topped with fondant icing.",
    isVegetarian: true,
    imageUrl: "/images/library/mille-feuille.jpg",
  },
  {
    name: "Tarte Tatin",
    category: "Desserts",
    cuisines: ["french","bistro","fine dining"],
    description: "A celebrated upside-down French apple tart with caramelized apples on a buttery, flaky pastry base.",
    isVegetarian: true,
    imageUrl: "/images/library/tarte-tatin.jpg",
  },
  {
    name: "Chocolate Mousse",
    category: "Desserts",
    cuisines: ["french","fine dining","bistro"],
    description: "An intensely rich, dark chocolate mousse, airy yet decadent, served chilled with a dollop of cream.",
    isVegetarian: true,
    isGlutenFree: true,
    imageUrl: "/images/library/chocolate-mousse.jpg",
  },
  {
    name: "Soufflé",
    category: "Desserts",
    cuisines: ["french","fine dining"],
    description: "A breathtaking, cloud-like baked French dessert that rises magically in the oven, flavored with chocolate or Grand Marnier.",
    isVegetarian: true,
    imageUrl: "/images/library/souffle.jpg",
  },
  {
    name: "Crêpes Suzette",
    category: "Desserts",
    cuisines: ["french","bistro","fine dining"],
    description: "Classic French crêpes in a caramelized orange and Grand Marnier butter sauce, flambéed tableside.",
    isVegetarian: true,
    imageUrl: "/images/library/crepes-suzette.jpg",
  },
  {
    name: "Éclair",
    category: "Desserts",
    cuisines: ["french","bakery","cafe"],
    description: "An elongated choux pastry filled with silky pastry cream and topped with a glossy chocolate glaze.",
    isVegetarian: true,
    imageUrl: "/images/library/eclair.jpg",
  },
  {
    name: "Panna Cotta",
    category: "Desserts",
    cuisines: ["italian","fine dining","bistro"],
    description: "An elegant Italian set cream dessert with a silky, wobbling texture, served with a fresh berry coulis.",
    isVegetarian: true,
    isGlutenFree: true,
    imageUrl: "/images/library/panna-cotta.jpg",
  },
  {
    name: "Cannoli",
    category: "Desserts",
    cuisines: ["italian","sicilian","bakery"],
    description: "Crispy fried pastry shells filled with sweet, creamy ricotta and studded with dark chocolate chips.",
    isVegetarian: true,
    imageUrl: "/images/library/cannoli.jpg",
  },
  {
    name: "Semifreddo",
    category: "Desserts",
    cuisines: ["italian","fine dining"],
    description: "A semi-frozen Italian dessert with a mousse-like texture, often flavored with pistachio, hazelnut, or berries.",
    isVegetarian: true,
    isGlutenFree: true,
    imageUrl: "/images/library/semifreddo.jpg",
  },
  {
    name: "Biscotti",
    category: "Desserts",
    cuisines: ["italian","cafe","bakery"],
    description: "Twice-baked Italian almond cookies, crunchy and dry, perfect for dunking into espresso or Vin Santo.",
    isVegetarian: true,
    imageUrl: "/images/library/biscotti.jpg",
  },
  {
    name: "Mochi",
    category: "Desserts",
    cuisines: ["japanese","asian","cafe"],
    description: "Soft, chewy Japanese rice cakes filled with sweet red bean paste or ice cream in beautiful pastel colors.",
    isVegetarian: true,
    isGlutenFree: true,
    imageUrl: "/images/library/mochi.jpg",
  },
  {
    name: "Matcha Ice Cream",
    category: "Desserts",
    cuisines: ["japanese","asian","cafe"],
    description: "Creamy, vibrant green ice cream made with premium ceremonial-grade matcha for a distinct, earthy sweetness.",
    isVegetarian: true,
    isGlutenFree: true,
    imageUrl: "/images/library/matcha-ice-cream.jpg",
  },
  {
    name: "Daifuku",
    category: "Desserts",
    cuisines: ["japanese","asian"],
    description: "A plump Japanese mochi stuffed with a generous filling of sweet red bean or white bean paste.",
    isVegetarian: true,
    isGlutenFree: true,
    imageUrl: "/images/library/daifuku.jpg",
  },
  {
    name: "Taiyaki",
    category: "Desserts",
    cuisines: ["japanese","asian"],
    description: "Fish-shaped Japanese waffles with a sweet filling of red bean, custard, or chocolate.",
    isVegetarian: true,
    imageUrl: "/images/library/taiyaki.jpg",
  },
  {
    name: "Kakigori",
    category: "Desserts",
    cuisines: ["japanese","asian"],
    description: "Finely shaved Japanese ice snow topped with colorful fruit syrups, condensed milk, and sweet toppings.",
    isVegan: true,
    isGlutenFree: true,
    imageUrl: "/images/library/kakigori.jpg",
  },
  {
    name: "Japanese Flan",
    category: "Desserts",
    cuisines: ["japanese","asian"],
    description: "A silky-smooth Japanese custard pudding with a light, wobbling texture and a dark caramel sauce.",
    isVegetarian: true,
    isGlutenFree: true,
    imageUrl: "/images/library/japanese-flan.jpg",
  },
  {
    name: "Rasgulla",
    category: "Desserts",
    cuisines: ["indian","bengali","south asian"],
    description: "Melt-in-the-mouth soft chenna cheese balls soaked in a light, fragrant sugar syrup.",
    isVegetarian: true,
    isGlutenFree: true,
    imageUrl: "/images/library/rasgulla.jpg",
  },
  {
    name: "Kheer",
    category: "Desserts",
    cuisines: ["indian","south asian"],
    description: "A creamy Indian rice pudding slow-cooked in whole milk with cardamom, saffron, and garnished with pistachios.",
    isVegetarian: true,
    isGlutenFree: true,
    imageUrl: "/images/library/kheer.jpg",
  },
  {
    name: "Jalebi",
    category: "Desserts",
    cuisines: ["indian","south asian","middle eastern"],
    description: "Crispy, coil-shaped deep-fried batter soaked in a vibrant saffron syrup — a beloved street food dessert.",
    isVegetarian: true,
    imageUrl: "/images/library/jalebi.jpg",
  },
  {
    name: "Kulfi",
    category: "Desserts",
    cuisines: ["indian","south asian"],
    description: "Traditional Indian ice cream, denser and richer than gelato, flavored with mango, pistachio, or rose.",
    isVegetarian: true,
    isGlutenFree: true,
    imageUrl: "/images/library/kulfi.jpg",
  },
  {
    name: "Gajar ka Halwa",
    category: "Desserts",
    cuisines: ["indian","punjabi","south asian"],
    description: "A slow-cooked North Indian carrot pudding made with grated carrots, whole milk, sugar, and ghee.",
    isVegetarian: true,
    isGlutenFree: true,
    imageUrl: "/images/library/gajar-ka-halwa.jpg",
  },
  {
    name: "Ladoo",
    category: "Desserts",
    cuisines: ["indian","south asian"],
    description: "Traditional Indian round sweets made from chickpea flour, ghee, and sugar, fragrant with cardamom.",
    isVegetarian: true,
    isGlutenFree: true,
    imageUrl: "/images/library/ladoo.jpg",
  },
  {
    name: "Barfi",
    category: "Desserts",
    cuisines: ["indian","south asian"],
    description: "A dense, fudgy Indian confection made from condensed milk and sugar, flavored with pistachio or rose.",
    isVegetarian: true,
    isGlutenFree: true,
    imageUrl: "/images/library/barfi.jpg",
  },
  {
    name: "Rasmalai",
    category: "Desserts",
    cuisines: ["indian","bengali","south asian"],
    description: "Flat chenna cheese patties soaked in chilled, saffron-infused cream, garnished with pistachio and rose petals.",
    isVegetarian: true,
    isGlutenFree: true,
    imageUrl: "/images/library/rasmalai.jpg",
  },
  {
    name: "Victoria Sponge",
    category: "Desserts",
    cuisines: ["british","bakery","afternoon tea"],
    description: "The quintessential British cake — two light sponge layers sandwiched with strawberry jam and whipped cream.",
    isVegetarian: true,
    imageUrl: "/images/library/victoria-sponge.jpg",
  },
  {
    name: "Bread and Butter Pudding",
    category: "Desserts",
    cuisines: ["british","irish"],
    description: "Buttered bread layered with raisins and baked in a rich custard, served warm with vanilla custard.",
    isVegetarian: true,
    imageUrl: "/images/library/bread-butter-pudding.jpg",
  },
  {
    name: "Trifle",
    category: "Desserts",
    cuisines: ["british","fine dining"],
    description: "An impressive layered British dessert of sponge cake, fruit jelly, crème anglaise, and whipped cream.",
    isVegetarian: true,
    imageUrl: "/images/library/trifle.jpg",
  },
  {
    name: "Churros with Chocolate Sauce",
    category: "Desserts",
    cuisines: ["mexican","spanish","latin american"],
    description: "Crispy, cinnamon-sugar-dusted fried dough served piping hot with a thick dark chocolate dipping sauce.",
    isVegetarian: true,
    imageUrl: "/images/library/churros-with-chocolate-sauce.jpg",
  },
  {
    name: "Tres Leches Cake",
    category: "Desserts",
    cuisines: ["mexican","latin american"],
    description: "A tender, milk-soaked sponge cake saturated with three types of milk and topped with whipped cream.",
    isVegetarian: true,
    imageUrl: "/images/library/tres-leches-cake.jpg",
  },
  {
    name: "Buñuelos",
    category: "Desserts",
    cuisines: ["mexican","spanish","latin american"],
    description: "Crispy, paper-thin fried pastry discs dusted with cinnamon sugar, a classic Mexican holiday treat.",
    isVegetarian: true,
    imageUrl: "/images/library/bunuelos.jpg",
  },
  {
    name: "Arroz con Leche",
    category: "Desserts",
    cuisines: ["mexican","spanish","latin american"],
    description: "A comforting rice pudding simmered in whole milk with cinnamon, vanilla, and condensed milk.",
    isVegetarian: true,
    isGlutenFree: true,
    imageUrl: "/images/library/arroz-con-leche.jpg",
  },
  {
    name: "Kunafa",
    category: "Desserts",
    cuisines: ["middle eastern","levantine","arabic"],
    description: "A spectacular Middle Eastern dessert of shredded phyllo pastry layered with sweet white cheese and drenched in sugar syrup.",
    isVegetarian: true,
    imageUrl: "/images/library/kunafa.jpg",
  },
  {
    name: "Basbousa",
    category: "Desserts",
    cuisines: ["middle eastern","egyptian","arabic"],
    description: "A moist, sweet semolina cake soaked in rose water syrup and garnished with whole almonds.",
    isVegetarian: true,
    imageUrl: "/images/library/basbousa.jpg",
  },
  {
    name: "Turkish Delight",
    category: "Desserts",
    cuisines: ["middle eastern","turkish","mediterranean"],
    description: "Soft, jewel-like confection with rosewater and mastic flavors, dusted with powdered sugar.",
    isVegan: true,
    isGlutenFree: true,
    imageUrl: "/images/library/turkish-delight.jpg",
  },
  {
    name: "Halva",
    category: "Desserts",
    cuisines: ["middle eastern","mediterranean","greek"],
    description: "A dense, crumbly confection made from tahini or semolina with honey, often studded with pistachios.",
    isVegan: true,
    imageUrl: "/images/library/halva.jpg",
  },
  {
    name: "Loukoumades",
    category: "Desserts",
    cuisines: ["greek","middle eastern","mediterranean"],
    description: "Greek honey puffs — light, airy fried dough balls drizzled with warm honey and sprinkled with cinnamon.",
    isVegetarian: true,
    imageUrl: "/images/library/loukoumades.jpg",
  },
  {
    name: "Brigadeiro",
    category: "Desserts",
    cuisines: ["brazilian","latin american"],
    description: "Brazil's beloved national sweet — fudgy chocolate truffles made from condensed milk and cocoa, rolled in sprinkles.",
    isVegetarian: true,
    isGlutenFree: true,
    imageUrl: "/images/library/brigadeiro.jpg",
  },
  {
    name: "Alfajores",
    category: "Desserts",
    cuisines: ["argentinian","latin american","spanish"],
    description: "Melt-in-your-mouth sandwich cookies filled with dulce de leche and dusted with powdered sugar.",
    isVegetarian: true,
    imageUrl: "/images/library/alfajores.jpg",
  },
  {
    name: "Dulce de Leche Crepes",
    category: "Desserts",
    cuisines: ["argentinian","latin american"],
    description: "Thin, delicate French-style crepes generously filled with rich, velvety Argentinian dulce de leche.",
    isVegetarian: true,
    imageUrl: "/images/library/dulce-de-leche-crepes.jpg",
  },
  {
    name: "Mango Sticky Rice",
    category: "Desserts",
    cuisines: ["thai","southeast asian","asian"],
    description: "Thailand's most iconic dessert — sweet glutinous rice soaked in coconut milk and served with ripe fresh mango.",
    isVegan: true,
    isGlutenFree: true,
    imageUrl: "/images/library/mango-sticky-rice.jpg",
  },
  {
    name: "Halo-Halo",
    category: "Desserts",
    cuisines: ["filipino","asian"],
    description: "The Philippines' extravagant shaved ice dessert layered with sweet beans, jellies, fruit, and ube ice cream.",
    isVegetarian: true,
    isGlutenFree: true,
    imageUrl: "/images/library/halo-halo.jpg",
  },
  {
    name: "Cendol",
    category: "Desserts",
    cuisines: ["malaysian","indonesian","southeast asian"],
    description: "A beloved Southeast Asian dessert of shaved ice with green rice flour jelly, coconut milk, and palm sugar.",
    isVegan: true,
    isGlutenFree: true,
    imageUrl: "/images/library/cendol.jpg",
  },
  {
    name: "Tang Yuan",
    category: "Desserts",
    cuisines: ["chinese","asian"],
    description: "Soft, chewy glutinous rice balls filled with black sesame or peanut paste, served in warm sweet ginger syrup.",
    isVegan: true,
    isGlutenFree: true,
    imageUrl: "/images/library/tang-yuan.jpg",
  },
];
