import { LibraryDish } from "./global-dish-library";

export const NEW_GLOBAL_ADDITIONS: LibraryDish[] = [
  // COCKTAILS & ALCOHOL
  {
    name: "Classic Margarita",
    category: "Drinks",
    cuisines: ["mexican", "cocktail"],
    description: "A perfect blend of silver tequila, fresh lime juice, and orange liqueur, served with a salted rim.",
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
    imageUrl: "/images/library/classic-margarita.jpg",
  },
  {
    name: "Mojito",
    category: "Drinks",
    cuisines: ["cuban", "cocktail"],
    description: "Refreshing rum cocktail muddled with fresh mint leaves, lime juice, sugar, and a splash of club soda.",
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
    imageUrl: "/images/library/mojito.jpg",
  },
  {
    name: "Old Fashioned",
    category: "Drinks",
    cuisines: ["american", "cocktail"],
    description: "Classic bourbon whiskey cocktail gently stirred with bitters, sugar, and an orange peel twist.",
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
    imageUrl: "/images/library/old-fashioned.jpg",
  },
  {
    name: "Aperol Spritz",
    category: "Drinks",
    cuisines: ["italian", "cocktail"],
    description: "Vibrant Italian aperitif made with Aperol, prosecco, and a splash of soda water over ice.",
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
    imageUrl: "/images/library/aperol-spritz.jpg",
  },
  {
    name: "Espresso Martini",
    category: "Drinks",
    cuisines: ["cocktail"],
    description: "A sophisticated after-dinner cocktail shaking premium vodka with fresh, dark espresso and coffee liqueur.",
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
    imageUrl: "/images/library/espresso-martini.jpg",
  },
  {
    name: "Piña Colada",
    category: "Drinks",
    cuisines: ["puerto rican", "cocktail"],
    description: "A tropical, creamy blend of light rum, coconut cream, and fresh pineapple juice.",
    isVegetarian: true,
    isGlutenFree: true,
    imageUrl: "/images/library/pi-a-colada.jpg",
  },
  {
    name: "Red Sangria",
    category: "Drinks",
    cuisines: ["spanish", "cocktail"],
    description: "Fruity Spanish wine punch made with robust red wine, brandy, and steeped fresh fruits.",
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
    imageUrl: "/images/library/red-sangria.jpg",
  },
  {
    name: "Craft IPA",
    category: "Drinks",
    cuisines: ["american", "beer"],
    description: "A bold, hoppy India Pale Ale featuring bright citrus and pine notes with a crisp bitter finish.",
    isVegetarian: true,
    isVegan: true,
    imageUrl: "/images/library/craft-ipa.jpg",
  },
  {
    name: "Cabernet Sauvignon",
    category: "Drinks",
    cuisines: ["wine"],
    description: "A full-bodied red wine with dark fruit flavors of black cherry, blackberry, and hints of cedar.",
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
    imageUrl: "/images/library/cabernet-sauvignon.jpg",
  },
  {
    name: "Chardonnay",
    category: "Drinks",
    cuisines: ["wine"],
    description: "A dry, medium to full-bodied white wine with crisp apple, pear, and subtle buttery oak notes.",
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
    imageUrl: "/images/library/chardonnay.jpg",
  },

  // SOFT DRINKS & CAFE
  {
    name: "Classic Cola",
    category: "Drinks",
    cuisines: ["american", "soda"],
    description: "The timeless, effervescent dark cola served ice cold with a slice of lemon.",
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
    imageUrl: "/images/library/classic-cola.jpg",
  },
  {
    name: "Diet Cola",
    category: "Drinks",
    cuisines: ["american", "soda"],
    description: "A zero-calorie version of the classic cola, offering crisp refreshment without the sugar.",
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
    imageUrl: "/images/library/diet-cola.jpg",
  },
  {
    name: "Lemon-Lime Soda",
    category: "Drinks",
    cuisines: ["american", "soda"],
    description: "A clear, crisp, and intensely refreshing citrus soda.",
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
    imageUrl: "/images/library/lemon-lime-soda.jpg",
  },
  {
    name: "Artisanal Lemonade",
    category: "Drinks",
    cuisines: ["american", "cafe"],
    description: "Freshly squeezed lemons lightly sweetened with cane sugar and served over crushed ice.",
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
    imageUrl: "/images/library/artisanal-lemonade.jpg",
  },
  {
    name: "Cold Brew Coffee",
    category: "Drinks",
    cuisines: ["cafe"],
    description: "Smooth, low-acidity coffee slow-steeped in cold water for 18 hours.",
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
    imageUrl: "/images/library/cold-brew-coffee.jpg",
  },
  {
    name: "Matcha Green Tea Latte",
    category: "Drinks",
    cuisines: ["japanese", "cafe"],
    description: "Ceremonial grade Japanese green tea whisked with creamy steamed milk and lightly sweetened.",
    isVegetarian: true,
    isGlutenFree: true,
    imageUrl: "/images/library/matcha-green-tea-latte.jpg",
  },
  {
    name: "Boba Milk Tea",
    category: "Drinks",
    cuisines: ["taiwanese", "cafe"],
    description: "Classic creamy black milk tea served chilled with chewy, sweet tapioca pearls.",
    isVegetarian: true,
    isGlutenFree: true,
    imageUrl: "/images/library/boba-milk-tea.jpg",
  },
  {
    name: "Freshly Brewed Iced Tea",
    category: "Drinks",
    cuisines: ["american", "cafe"],
    description: "Crisp black tea brewed fresh daily, served chilled over ice with a lemon wedge.",
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
    imageUrl: "/images/library/freshly-brewed-iced-tea.jpg",
  },

  // GLOBAL SWEETS
  {
    name: "Churros con Chocolate",
    category: "Desserts",
    cuisines: ["spanish", "mexican"],
    description: "Crispy fried dough pastries coated in cinnamon sugar, served with a thick, warm dark chocolate dipping sauce.",
    isVegetarian: true,
    imageUrl: "/images/library/churros-con-chocolate.jpg",
  },
  {
    name: "Baklava",
    category: "Desserts",
    cuisines: ["turkish", "greek", "middle eastern"],
    description: "Layers of incredibly flaky phyllo dough, chopped pistachios, and walnuts, drenched in sweet honey syrup.",
    isVegetarian: true,
    imageUrl: "/images/library/baklava.jpg",
  },
  {
    name: "Mochi Ice Cream",
    category: "Desserts",
    cuisines: ["japanese"],
    description: "Bite-sized scoops of premium ice cream enveloped in a sweet, soft, and chewy rice dough.",
    isVegetarian: true,
    isGlutenFree: true,
    imageUrl: "/images/library/mochi-ice-cream.jpg",
  },
  {
    name: "Tiramisu",
    category: "Desserts",
    cuisines: ["italian"],
    description: "Classic Italian dessert made of ladyfingers dipped in espresso, layered with a whipped mascarpone cream and dusted with cocoa.",
    isVegetarian: true,
    imageUrl: "/images/library/tiramisu.jpg",
  },
  {
    name: "Cannoli Siciliani",
    category: "Desserts",
    cuisines: ["italian"],
    description: "Crispy, tube-shaped pastry shells filled with a sweet, creamy ricotta and chocolate chip filling.",
    isVegetarian: true,
    imageUrl: "/images/library/cannoli-siciliani.jpg",
  },
  {
    name: "Matcha Crepe Cake",
    category: "Desserts",
    cuisines: ["french", "japanese"],
    description: "Twenty delicate, paper-thin handmade crepes layered with light matcha-infused pastry cream.",
    isVegetarian: true,
    imageUrl: "/images/library/matcha-crepe-cake.jpg",
  },
  {
    name: "Gulab Jamun",
    category: "Desserts",
    cuisines: ["indian"],
    description: "Soft, melt-in-your-mouth milk solid dumplings deep-fried and soaked in a warm rose-water and cardamom syrup.",
    isVegetarian: true,
    imageUrl: "/images/library/gulab-jamun.jpg",
  },

  // GLOBAL SNACKS & APPETIZERS
  {
    name: "Vegetable Samosas",
    category: "Starters",
    cuisines: ["indian", "street food"],
    description: "Crispy, golden, pyramid-shaped pastries stuffed with spiced potatoes and peas, served with mint chutney.",
    isVegetarian: true,
    isVegan: true,
    isSpicy: true,
    imageUrl: "/images/library/vegetable-samosas.jpg",
  },
  {
    name: "Beef Empanadas",
    category: "Starters",
    cuisines: ["argentine", "latin american"],
    description: "Flaky, baked pastry crescents generously stuffed with seasoned ground beef, onions, olives, and hard-boiled egg.",
    imageUrl: "/images/library/beef-empanadas.jpg",
  },
  {
    name: "Takoyaki",
    category: "Starters",
    cuisines: ["japanese", "street food"],
    description: "Savory, round batter balls filled with diced octopus, topped with sweet sauce, mayo, and dancing bonito flakes.",
    imageUrl: "/images/library/takoyaki.jpg",
  },
  {
    name: "Crispy Spring Rolls",
    category: "Starters",
    cuisines: ["chinese", "vietnamese", "asian"],
    description: "Light and shattered-glass crispy wrappers filled with shredded cabbage, carrots, and glass noodles, served with sweet chili sauce.",
    isVegetarian: true,
    isVegan: true,
    imageUrl: "/images/library/crispy-spring-rolls.jpg",
  },
  {
    name: "Pork Gyoza",
    category: "Starters",
    cuisines: ["japanese", "asian"],
    description: "Juicy pork and cabbage dumplings, pan-fried to achieve a crispy bottom and steamed top, served with soy dipping sauce.",
    imageUrl: "/images/library/pork-gyoza.jpg",
  },
  {
    name: "Bao Buns",
    category: "Starters",
    cuisines: ["chinese", "taiwanese"],
    description: "Soft, fluffy steamed buns filled with slow-braised pork belly, hoisin sauce, pickled cucumbers, and crushed peanuts.",
    imageUrl: "/images/library/bao-buns.jpg",
  }
];
