import json

american_dishes = [
    # Starters (10)
    {"name": "Loaded Potato Skins", "category": "Starters", "cuisines": ["american diner", "pub"], "description": "Crispy potato skins loaded with melted cheddar, bacon bits, sour cream, and green onions.", "suggestedCookingTime": 15},
    {"name": "Buffalo Chicken Wings", "category": "Starters", "cuisines": ["american diner", "pub"], "description": "Classic upstate NY wings tossed in spicy buffalo sauce, served with celery and blue cheese dip.", "isSpicy": True, "suggestedCookingTime": 20},
    {"name": "Mozzarella Sticks", "category": "Starters", "cuisines": ["american diner", "fast food"], "description": "Golden-fried cheese sticks served with a side of warm marinara sauce for dipping.", "isVegetarian": True, "suggestedCookingTime": 10},
    {"name": "Spinach Artichoke Dip", "category": "Starters", "cuisines": ["american diner"], "description": "A creamy, bubbling hot dip of spinach, artichoke hearts, and parmesan, served with tortilla chips.", "isVegetarian": True, "suggestedCookingTime": 15},
    {"name": "Fried Pickles", "category": "Starters", "cuisines": ["american diner", "southern"], "description": "Tangy dill pickle slices breaded and deep-fried, served with ranch dressing.", "isVegetarian": True, "suggestedCookingTime": 10},
    {"name": "Onion Rings", "category": "Starters", "cuisines": ["american diner", "fast food"], "description": "Thick-cut, beer-battered onion rings fried to a perfect golden crunch.", "isVegetarian": True, "suggestedCookingTime": 10},
    {"name": "Clam Chowder", "category": "Starters", "cuisines": ["american diner", "seafood"], "description": "Rich, creamy New England soup packed with tender clams, potatoes, and bacon.", "suggestedCookingTime": 25},
    {"name": "Jalapeño Poppers", "category": "Starters", "cuisines": ["american diner", "tex-mex"], "description": "Fresh jalapeños stuffed with cream cheese, breaded, and fried until golden brown.", "isVegetarian": True, "isSpicy": True, "suggestedCookingTime": 15},
    {"name": "Mini Sliders", "category": "Starters", "cuisines": ["american diner", "pub"], "description": "Three bite-sized beef burgers topped with American cheese, pickles, and ketchup.", "suggestedCookingTime": 15},
    {"name": "Deviled Eggs", "category": "Starters", "cuisines": ["american diner", "southern"], "description": "Hard-boiled egg halves filled with a creamy, mustard-spiked yolk mixture and dusted with paprika.", "isVegetarian": True, "isGlutenFree": True, "suggestedCookingTime": 10},

    # Mains (20)
    {"name": "Classic Cheeseburger", "category": "Main Courses", "cuisines": ["american diner", "fast food"], "description": "A juicy beef patty topped with melted American cheese, lettuce, tomato, onion, and signature sauce on a toasted bun.", "suggestedCookingTime": 15},
    {"name": "BBQ Pork Ribs", "category": "Main Courses", "cuisines": ["american diner", "bbq"], "description": "A half rack of slow-smoked pork ribs slathered in a sweet and tangy hickory barbecue sauce.", "isGlutenFree": True, "suggestedCookingTime": 180},
    {"name": "Fried Chicken", "category": "Main Courses", "cuisines": ["american diner", "southern"], "description": "Crispy, buttermilk-marinated fried chicken served with a side of creamy coleslaw and a biscuit.", "suggestedCookingTime": 25},
    {"name": "Philly Cheesesteak", "category": "Main Courses", "cuisines": ["american diner"], "description": "Thinly sliced ribeye steak grilled with onions and topped with melted provolone on a hoagie roll.", "suggestedCookingTime": 15},
    {"name": "Macaroni and Cheese", "category": "Main Courses", "cuisines": ["american diner", "southern"], "description": "A massive bowl of elbow macaroni baked in a rich, velvety sharp cheddar cheese sauce with a crispy breadcrumb topping.", "isVegetarian": True, "suggestedCookingTime": 25},
    {"name": "Meatloaf", "category": "Main Courses", "cuisines": ["american diner"], "description": "Homestyle baked beef meatloaf topped with a sweet tomato glaze, served alongside mashed potatoes.", "suggestedCookingTime": 45},
    {"name": "Chicken Fried Steak", "category": "Main Courses", "cuisines": ["american diner", "southern"], "description": "Tenderized beef steak, breaded and fried like chicken, smothered in rich country pepper gravy.", "suggestedCookingTime": 20},
    {"name": "Pulled Pork Sandwich", "category": "Main Courses", "cuisines": ["american diner", "bbq"], "description": "Slow-smoked pork shoulder piled high on a brioche bun, topped with tangy slaw and BBQ sauce.", "suggestedCookingTime": 15},
    {"name": "Grilled Cheese & Tomato Soup", "category": "Main Courses", "cuisines": ["american diner"], "description": "A buttery, gooey grilled cheddar cheese sandwich served with a comforting bowl of creamy tomato soup.", "isVegetarian": True, "suggestedCookingTime": 15},
    {"name": "BLT Sandwich", "category": "Main Courses", "cuisines": ["american diner"], "description": "Crispy thick-cut bacon, fresh iceberg lettuce, and ripe tomatoes with mayo on toasted sourdough.", "suggestedCookingTime": 10},
    {"name": "New York Strip Steak", "category": "Main Courses", "cuisines": ["american diner", "steakhouse"], "description": "A prime 12oz NY Strip steak grilled to order, served with garlic herb butter.", "isGlutenFree": True, "suggestedCookingTime": 25},
    {"name": "Cobb Salad", "category": "Main Courses", "cuisines": ["american diner"], "description": "A hearty salad composed of chopped greens, grilled chicken, bacon, hard-boiled egg, avocado, and blue cheese.", "isGlutenFree": True, "suggestedCookingTime": 15},
    {"name": "Hot Dog with Chili", "category": "Main Courses", "cuisines": ["american diner", "fast food"], "description": "An all-beef frankfurter topped with hearty beef chili, diced onions, and yellow mustard.", "suggestedCookingTime": 10},
    {"name": "Jambalaya", "category": "Main Courses", "cuisines": ["american diner", "cajun"], "description": "A spicy Louisiana rice dish packed with shrimp, chicken, and Andouille sausage.", "isSpicy": True, "isGlutenFree": True, "suggestedCookingTime": 45},
    {"name": "Shrimp and Grits", "category": "Main Courses", "cuisines": ["american diner", "southern"], "description": "Plump sautéed shrimp served over creamy, cheesy stone-ground grits with bacon and scallions.", "suggestedCookingTime": 25},
    {"name": "Club Sandwich", "category": "Main Courses", "cuisines": ["american diner"], "description": "A triple-decker sandwich stacked with roasted turkey, ham, bacon, lettuce, tomato, and mayo.", "suggestedCookingTime": 15},
    {"name": "Beef Brisket", "category": "Main Courses", "cuisines": ["american diner", "bbq"], "description": "Slow-smoked Texas-style beef brisket, sliced thick and served with pickles and onions.", "isGlutenFree": True, "suggestedCookingTime": 720},
    {"name": "Lobster Roll", "category": "Main Courses", "cuisines": ["american diner", "seafood"], "description": "Chilled, sweet Maine lobster meat lightly dressed with mayo, served in a butter-toasted split-top bun.", "suggestedCookingTime": 15},
    {"name": "Chicken Pot Pie", "category": "Main Courses", "cuisines": ["american diner"], "description": "A comforting, creamy stew of chicken and vegetables baked under a flaky, golden pastry crust.", "suggestedCookingTime": 45},
    {"name": "Bacon Cheeseburger", "category": "Main Courses", "cuisines": ["american diner"], "description": "Our classic cheeseburger elevated with two slices of thick-cut, crispy smoked bacon.", "suggestedCookingTime": 15},

    # Sides (10)
    {"name": "French Fries", "category": "Sides", "cuisines": ["american diner", "fast food"], "description": "Classic shoestring potatoes fried until crispy and tossed with sea salt.", "isVegetarian": True, "isVegan": True, "suggestedCookingTime": 10},
    {"name": "Coleslaw", "category": "Sides", "cuisines": ["american diner", "bbq"], "description": "Shredded cabbage and carrots in a creamy, tangy, sweet mayonnaise dressing.", "isVegetarian": True, "isGlutenFree": True, "suggestedCookingTime": 5},
    {"name": "Baked Potato", "category": "Sides", "cuisines": ["american diner", "steakhouse"], "description": "A large Idaho potato baked until tender, served with butter, sour cream, and chives.", "isVegetarian": True, "isGlutenFree": True, "suggestedCookingTime": 60},
    {"name": "Corn on the Cob", "category": "Sides", "cuisines": ["american diner", "bbq"], "description": "Sweet corn boiled and slathered with melted butter.", "isVegetarian": True, "isGlutenFree": True, "suggestedCookingTime": 15},
    {"name": "Hush Puppies", "category": "Sides", "cuisines": ["american diner", "southern"], "description": "Deep-fried, savory cornbread balls.", "isVegetarian": True, "suggestedCookingTime": 10},
    {"name": "Tater Tots", "category": "Sides", "cuisines": ["american diner", "fast food"], "description": "Crispy, golden, bite-sized potato cylinders, a diner classic.", "isVegetarian": True, "isVegan": True, "suggestedCookingTime": 10},
    {"name": "Mashed Potatoes & Gravy", "category": "Sides", "cuisines": ["american diner", "southern"], "description": "Creamy mashed potatoes topped with rich brown beef gravy.", "suggestedCookingTime": 20},
    {"name": "Baked Beans", "category": "Sides", "cuisines": ["american diner", "bbq"], "description": "Sweet and savory navy beans slow-baked with molasses and bacon.", "isGlutenFree": True, "suggestedCookingTime": 60},
    {"name": "Sweet Potato Fries", "category": "Sides", "cuisines": ["american diner"], "description": "Crispy fried sweet potato strips served with a side of honey mustard.", "isVegetarian": True, "isVegan": True, "suggestedCookingTime": 15},
    {"name": "Buttermilk Biscuits", "category": "Sides", "cuisines": ["american diner", "southern"], "description": "Two warm, flaky, freshly baked buttermilk biscuits served with honey butter.", "isVegetarian": True, "suggestedCookingTime": 20},

    # Desserts (10)
    {"name": "New York Cheesecake", "category": "Desserts", "cuisines": ["american diner", "bakery"], "description": "A dense, rich, and creamy cheese filling baked on a graham cracker crust.", "isVegetarian": True, "suggestedCookingTime": 0},
    {"name": "Apple Pie", "category": "Desserts", "cuisines": ["american diner", "bakery"], "description": "Classic double-crust pie filled with spiced, tender apples, served warm.", "isVegetarian": True, "suggestedCookingTime": 15},
    {"name": "Chocolate Brownie Sundae", "category": "Desserts", "cuisines": ["american diner"], "description": "A warm, fudgy chocolate brownie topped with vanilla ice cream, hot fudge, and a cherry.", "isVegetarian": True, "suggestedCookingTime": 5},
    {"name": "Pecan Pie", "category": "Desserts", "cuisines": ["american diner", "southern"], "description": "A sweet, gooey caramel filling loaded with toasted pecans in a flaky crust.", "isVegetarian": True, "suggestedCookingTime": 0},
    {"name": "Key Lime Pie", "category": "Desserts", "cuisines": ["american diner", "seafood"], "description": "Tart and sweet key lime custard baked in a graham cracker crust, topped with whipped cream.", "isVegetarian": True, "suggestedCookingTime": 0},
    {"name": "Banana Split", "category": "Desserts", "cuisines": ["american diner", "cafe"], "description": "A classic ice cream parlor treat featuring vanilla, chocolate, and strawberry scoops over a split banana.", "isVegetarian": True, "isGlutenFree": True, "suggestedCookingTime": 5},
    {"name": "Milkshake", "category": "Desserts", "cuisines": ["american diner", "fast food"], "description": "A thick, old-fashioned hand-spun milkshake (choice of Vanilla, Chocolate, or Strawberry).", "isVegetarian": True, "isGlutenFree": True, "suggestedCookingTime": 5},
    {"name": "Chocolate Chip Cookies", "category": "Desserts", "cuisines": ["american diner", "bakery"], "description": "Three oversized, warm, gooey chocolate chip cookies served fresh from the oven.", "isVegetarian": True, "suggestedCookingTime": 15},
    {"name": "Red Velvet Cake", "category": "Desserts", "cuisines": ["american diner", "southern"], "description": "A slice of moist crimson cocoa cake layered with tangy cream cheese frosting.", "isVegetarian": True, "suggestedCookingTime": 0},
    {"name": "S'mores", "category": "Desserts", "cuisines": ["american diner"], "description": "A campfire classic made indoors: toasted marshmallows and melted chocolate sandwiched between graham crackers.", "isVegetarian": True, "suggestedCookingTime": 5}
]

mexican_dishes = [
    # Starters (10)
    {"name": "Guacamole & Chips", "category": "Starters", "cuisines": ["mexican", "taqueria"], "description": "Freshly mashed avocados mixed with lime, cilantro, jalapeño, and onions. Served with warm tortilla chips.", "isVegan": True, "isGlutenFree": True, "suggestedCookingTime": 10},
    {"name": "Queso Fundido", "category": "Starters", "cuisines": ["mexican"], "description": "A bubbling cast-iron skillet of melted Oaxaca cheese topped with spicy chorizo, served with warm flour tortillas.", "isSpicy": True, "suggestedCookingTime": 15},
    {"name": "Pico de Gallo", "category": "Starters", "cuisines": ["mexican", "taqueria"], "description": "A refreshing, chunky salsa of fresh tomatoes, onions, cilantro, and serrano peppers.", "isVegan": True, "isGlutenFree": True, "suggestedCookingTime": 5},
    {"name": "Ceviche de Camarón", "category": "Starters", "cuisines": ["mexican", "seafood"], "description": "Shrimp cured in fresh lime juice with tomatoes, onions, cilantro, and avocado.", "isGlutenFree": True, "suggestedCookingTime": 20},
    {"name": "Nachos Supremos", "category": "Starters", "cuisines": ["mexican", "tex-mex"], "description": "A mountain of tortilla chips smothered in melted cheese, beans, jalapeños, sour cream, and pico de gallo.", "isVegetarian": True, "isGlutenFree": True, "suggestedCookingTime": 15},
    {"name": "Elote", "category": "Starters", "cuisines": ["mexican", "street food"], "description": "Mexican street corn on the cob, slathered in mayo, cotija cheese, chili powder, and lime.", "isVegetarian": True, "isGlutenFree": True, "isSpicy": True, "suggestedCookingTime": 15},
    {"name": "Taquitos Dorados", "category": "Starters", "cuisines": ["mexican"], "description": "Crispy rolled corn tortillas filled with shredded chicken, topped with lettuce, crema, and salsa verde.", "isGlutenFree": True, "suggestedCookingTime": 15},
    {"name": "Sopa de Tortilla", "category": "Starters", "cuisines": ["mexican"], "description": "A rich tomato-chili broth poured over crispy tortilla strips, topped with avocado and queso fresco.", "isVegetarian": True, "isGlutenFree": True, "suggestedCookingTime": 20},
    {"name": "Tostada de Tinga", "category": "Starters", "cuisines": ["mexican"], "description": "A crisp, flat tortilla topped with refried beans and shredded chicken in a smoky chipotle sauce.", "isSpicy": True, "isGlutenFree": True, "suggestedCookingTime": 10},
    {"name": "Chiles Toreados", "category": "Starters", "cuisines": ["mexican", "taqueria"], "description": "Blister-fried jalapeño and serrano peppers seasoned with soy sauce and lime.", "isVegan": True, "isGlutenFree": True, "isSpicy": True, "suggestedCookingTime": 10},

    # Mains (20)
    {"name": "Tacos al Pastor", "category": "Main Courses", "cuisines": ["mexican", "taqueria"], "description": "Three corn tortillas filled with spit-roasted marinated pork, pineapple, cilantro, and onions.", "isGlutenFree": True, "suggestedCookingTime": 15},
    {"name": "Enchiladas Verdes", "category": "Main Courses", "cuisines": ["mexican"], "description": "Corn tortillas rolled with shredded chicken, baked in a tangy tomatillo salsa and topped with melted cheese.", "isGlutenFree": True, "suggestedCookingTime": 25},
    {"name": "Fajitas de Pollo", "category": "Main Courses", "cuisines": ["mexican", "tex-mex"], "description": "Sizzling strips of grilled chicken breast with bell peppers and onions, served with tortillas and guacamole.", "suggestedCookingTime": 20},
    {"name": "Carne Asada", "category": "Main Courses", "cuisines": ["mexican", "taqueria"], "description": "Thinly sliced, citrus-marinated skirt steak grilled over an open flame, served with rice and beans.", "isGlutenFree": True, "suggestedCookingTime": 20},
    {"name": "Mole Poblano", "category": "Main Courses", "cuisines": ["mexican"], "description": "A complex, rich, and dark sauce made of chilies and chocolate, poured over tender chicken pieces.", "suggestedCookingTime": 45},
    {"name": "Burrito de Asada", "category": "Main Courses", "cuisines": ["mexican", "tex-mex", "taqueria"], "description": "A massive flour tortilla stuffed with grilled steak, rice, beans, cheese, and pico de gallo.", "suggestedCookingTime": 15},
    {"name": "Quesadilla de Huitlacoche", "category": "Main Courses", "cuisines": ["mexican"], "description": "A blue corn tortilla folded over melted Oaxaca cheese and earthy Mexican corn truffle.", "isVegetarian": True, "isGlutenFree": True, "suggestedCookingTime": 10},
    {"name": "Chiles Rellenos", "category": "Main Courses", "cuisines": ["mexican"], "description": "Poblano peppers roasted, stuffed with cheese, battered, fried, and smothered in tomato sauce.", "isVegetarian": True, "suggestedCookingTime": 35},
    {"name": "Pozole Rojo", "category": "Main Courses", "cuisines": ["mexican"], "description": "A hearty traditional soup made with hominy corn, slow-cooked pork, and a rich red chili broth.", "isGlutenFree": True, "isSpicy": True, "suggestedCookingTime": 60},
    {"name": "Tacos de Carnitas", "category": "Main Courses", "cuisines": ["mexican", "taqueria"], "description": "Slow-cooked, tender pulled pork crisp-fried in its own fat, served on corn tortillas with salsa verde.", "isGlutenFree": True, "suggestedCookingTime": 15},
    {"name": "Camarones al la Diabla", "category": "Main Courses", "cuisines": ["mexican", "seafood"], "description": "Plump shrimp sautéed in an intensely fiery, bright red chili sauce, served with rice.", "isGlutenFree": True, "isSpicy": True, "suggestedCookingTime": 20},
    {"name": "Chimichanga", "category": "Main Courses", "cuisines": ["mexican", "tex-mex"], "description": "A large burrito filled with shredded beef and cheese, deep-fried until golden and crispy.", "suggestedCookingTime": 20},
    {"name": "Tacos de Pescado", "category": "Main Courses", "cuisines": ["mexican", "seafood"], "description": "Baja-style crispy battered fish served in tortillas with shredded cabbage and a creamy white sauce.", "suggestedCookingTime": 15},
    {"name": "Tamales de Puerco", "category": "Main Courses", "cuisines": ["mexican"], "description": "Corn dough filled with spicy red chili pork, wrapped in a corn husk and steamed.", "isGlutenFree": True, "suggestedCookingTime": 45},
    {"name": "Sopes con Chorizo", "category": "Main Courses", "cuisines": ["mexican", "street food"], "description": "Thick corn masa boats topped with refried beans, spicy crumbled chorizo, lettuce, and crema.", "isGlutenFree": True, "suggestedCookingTime": 20},
    {"name": "Barbacoa de Res", "category": "Main Courses", "cuisines": ["mexican"], "description": "Beef cheek slow-steamed until incredibly tender, served with tortillas, cilantro, and onions.", "isGlutenFree": True, "suggestedCookingTime": 60},
    {"name": "Tlayuda", "category": "Main Courses", "cuisines": ["mexican"], "description": "Oaxacan 'pizza'—a massive crispy tortilla topped with refried beans, Oaxaca cheese, and sliced meats.", "isGlutenFree": True, "suggestedCookingTime": 15},
    {"name": "Enchiladas Suizas", "category": "Main Courses", "cuisines": ["mexican"], "description": "Chicken enchiladas baked in a creamy, mild green tomatillo sauce topped with melted Swiss cheese.", "isGlutenFree": True, "suggestedCookingTime": 25},
    {"name": "Cochinita Pibil", "category": "Main Courses", "cuisines": ["mexican"], "description": "Yucatan-style slow-roasted pork marinated in achiote and citrus, wrapped in banana leaves.", "isGlutenFree": True, "suggestedCookingTime": 60},
    {"name": "Fajitas Vegetarianas", "category": "Main Courses", "cuisines": ["mexican", "tex-mex"], "description": "A sizzling platter of grilled bell peppers, onions, zucchini, and mushrooms with tortillas.", "isVegetarian": True, "isVegan": True, "suggestedCookingTime": 20},

    # Sides (10)
    {"name": "Arroz Mexicano", "category": "Sides", "cuisines": ["mexican"], "description": "Fluffy, savory rice cooked in a tomato and chicken broth with peas and carrots.", "isGlutenFree": True, "suggestedCookingTime": 25},
    {"name": "Frijoles Refritos", "category": "Sides", "cuisines": ["mexican"], "description": "Pinto beans cooked until tender and mashed with a hint of onion and garlic.", "isVegetarian": True, "isGlutenFree": True, "suggestedCookingTime": 20},
    {"name": "Frijoles Charros", "category": "Sides", "cuisines": ["mexican"], "description": "A flavorful, soupy bowl of pinto beans stewed with bacon, chorizo, jalapeños, and tomatoes.", "isGlutenFree": True, "isSpicy": True, "suggestedCookingTime": 45},
    {"name": "Tortillas de Maíz Hechas a Mano", "category": "Sides", "cuisines": ["mexican", "taqueria"], "description": "A stack of warm, fresh, handmade corn tortillas.", "isVegan": True, "isGlutenFree": True, "suggestedCookingTime": 10},
    {"name": "Cebollitas Asadas", "category": "Sides", "cuisines": ["mexican", "taqueria"], "description": "Grilled knob onions charred over an open flame with lime and salt.", "isVegan": True, "isGlutenFree": True, "suggestedCookingTime": 10},
    {"name": "Nopales en Ensalada", "category": "Sides", "cuisines": ["mexican"], "description": "A refreshing salad made of tender cactus paddles, tomatoes, onions, cilantro, and lime.", "isVegan": True, "isGlutenFree": True, "suggestedCookingTime": 15},
    {"name": "Plátanos Fritos", "category": "Sides", "cuisines": ["mexican"], "description": "Sweet plantains fried until caramelized, often served with a drizzle of crema.", "isVegetarian": True, "isGlutenFree": True, "suggestedCookingTime": 15},
    {"name": "Salsa Roja y Verde", "category": "Sides", "cuisines": ["mexican", "taqueria"], "description": "A side serving of our house-made spicy red and tangy green salsas.", "isVegan": True, "isGlutenFree": True, "isSpicy": True, "suggestedCookingTime": 5},
    {"name": "Chicharrón", "category": "Sides", "cuisines": ["mexican", "street food"], "description": "Crispy, puffy fried pork rinds, perfect for dipping in salsa or guacamole.", "isGlutenFree": True, "suggestedCookingTime": 5},
    {"name": "Calabacitas con Elote", "category": "Sides", "cuisines": ["mexican"], "description": "Zucchini sautéed with sweet corn kernels, tomatoes, and onions.", "isVegan": True, "isGlutenFree": True, "suggestedCookingTime": 15},

    # Desserts (10)
    {"name": "Churros con Chocolate", "category": "Desserts", "cuisines": ["mexican", "street food", "bakery"], "description": "Crispy, star-shaped dough piped and fried, dusted in cinnamon sugar, served with a rich chocolate dip.", "isVegetarian": True, "suggestedCookingTime": 15},
    {"name": "Flan de Vainilla", "category": "Desserts", "cuisines": ["mexican"], "description": "A rich, silky vanilla custard baked with a layer of clear caramel sauce.", "isVegetarian": True, "isGlutenFree": True, "suggestedCookingTime": 0},
    {"name": "Tres Leches Cake", "category": "Desserts", "cuisines": ["mexican", "bakery"], "description": "A light sponge cake soaked in three kinds of milk, topped with fluffy whipped cream.", "isVegetarian": True, "suggestedCookingTime": 0},
    {"name": "Arroz con Leche", "category": "Desserts", "cuisines": ["mexican"], "description": "Comforting Mexican rice pudding spiced with cinnamon and sweetened with condensed milk.", "isVegetarian": True, "isGlutenFree": True, "suggestedCookingTime": 0},
    {"name": "Sopapillas", "category": "Desserts", "cuisines": ["mexican", "tex-mex"], "description": "Puffy, deep-fried pastry pillows drizzled with warm honey and powdered sugar.", "isVegetarian": True, "suggestedCookingTime": 10},
    {"name": "Nieve de Garrafa", "category": "Desserts", "cuisines": ["mexican"], "description": "Traditional artisanal Mexican water-based ice cream (sorbet), ask for today's fruit flavors.", "isVegan": True, "isGlutenFree": True, "suggestedCookingTime": 0},
    {"name": "Carlota de Limón", "category": "Desserts", "cuisines": ["mexican"], "description": "An icebox cake made with layers of Maria cookies and a creamy, tart lime filling.", "isVegetarian": True, "suggestedCookingTime": 0},
    {"name": "Paletas", "category": "Desserts", "cuisines": ["mexican", "street food"], "description": "Fresh fruit popsicles made in-house with natural ingredients.", "isVegan": True, "isGlutenFree": True, "suggestedCookingTime": 0},
    {"name": "Empanadas Dulces", "category": "Desserts", "cuisines": ["mexican", "bakery"], "description": "Baked pastry turnovers filled with sweet cajeta (caramel) or fruit preserves.", "isVegetarian": True, "suggestedCookingTime": 15},
    {"name": "Capirotada", "category": "Desserts", "cuisines": ["mexican"], "description": "Mexican bread pudding layered with nuts, cheese, raisins, and a spiced piloncillo syrup.", "isVegetarian": True, "suggestedCookingTime": 0}
]

japanese_dishes = [
    # Starters (10)
    {"name": "Edamame", "category": "Starters", "cuisines": ["japanese", "sushi", "izakaya"], "description": "Lightly boiled young soybeans served in the pod and dusted with coarse sea salt.", "isVegan": True, "isGlutenFree": True, "suggestedCookingTime": 5},
    {"name": "Gyoza", "category": "Starters", "cuisines": ["japanese", "ramen", "izakaya"], "description": "Six pan-fried dumplings filled with seasoned pork and cabbage, served with a soy-vinegar dip.", "suggestedCookingTime": 10},
    {"name": "Agedashi Tofu", "category": "Starters", "cuisines": ["japanese", "izakaya"], "description": "Lightly deep-fried silken tofu served in a hot, savory dashi broth with grated daikon and scallions.", "isVegetarian": True, "suggestedCookingTime": 15},
    {"name": "Miso Soup", "category": "Starters", "cuisines": ["japanese", "sushi", "teishoku"], "description": "Traditional soup made with fermented soybean paste, dashi, tofu cubes, and wakame seaweed.", "suggestedCookingTime": 5},
    {"name": "Takoyaki", "category": "Starters", "cuisines": ["japanese", "street food", "izakaya"], "description": "Golden, savory battered octopus balls drizzled with sweet sauce, mayo, and bonito flakes.", "suggestedCookingTime": 15},
    {"name": "Wakame Salad", "category": "Starters", "cuisines": ["japanese", "sushi"], "description": "A bright green seaweed salad dressed with a sweet sesame and soy vinaigrette.", "isVegan": True, "isGlutenFree": True, "suggestedCookingTime": 5},
    {"name": "Yakitori", "category": "Starters", "cuisines": ["japanese", "izakaya", "street food"], "description": "Three skewers of charcoal-grilled chicken thigh glazed with a sweet and savory tare sauce.", "isGlutenFree": True, "suggestedCookingTime": 15},
    {"name": "Tuna Tataki", "category": "Starters", "cuisines": ["japanese", "sushi", "izakaya"], "description": "Lightly seared, rare tuna slices served with a citrusy ponzu sauce and sliced scallions.", "isGlutenFree": True, "suggestedCookingTime": 10},
    {"name": "Karaage", "category": "Starters", "cuisines": ["japanese", "izakaya"], "description": "Japanese-style bite-sized fried chicken, marinated in soy sauce, ginger, and garlic, served with lemon.", "suggestedCookingTime": 15},
    {"name": "Chawanmushi", "category": "Starters", "cuisines": ["japanese", "fine dining"], "description": "A delicate, savory steamed egg custard served in a cup, containing shrimp, chicken, and shiitake mushrooms.", "isGlutenFree": True, "suggestedCookingTime": 20},

    # Mains (20)
    {"name": "Tonkotsu Ramen", "category": "Main Courses", "cuisines": ["japanese", "ramen"], "description": "Hakata-style ramen featuring a rich, milky pork bone broth, thin noodles, chashu pork, and a soft-boiled egg.", "suggestedCookingTime": 15},
    {"name": "Sushi Nigiri Platter", "category": "Main Courses", "cuisines": ["japanese", "sushi"], "description": "Chef's selection of 10 premium pieces of raw fish over seasoned vinegared rice.", "isGlutenFree": True, "suggestedCookingTime": 20},
    {"name": "Sashimi Moriawase", "category": "Main Courses", "cuisines": ["japanese", "sushi"], "description": "A stunning assortment of the day's freshest raw fish, elegantly sliced and plated.", "isGlutenFree": True, "suggestedCookingTime": 15},
    {"name": "Katsudon", "category": "Main Courses", "cuisines": ["japanese", "teishoku"], "description": "A comforting bowl of rice topped with a breaded, deep-fried pork cutlet, egg, and onions simmered in sweet soy broth.", "suggestedCookingTime": 20},
    {"name": "Chicken Teriyaki", "category": "Main Courses", "cuisines": ["japanese", "teishoku"], "description": "Grilled chicken breast glazed in a sweet, sticky soy-based sauce, served with steamed rice and vegetables.", "suggestedCookingTime": 20},
    {"name": "Tempura Udon", "category": "Main Courses", "cuisines": ["japanese"], "description": "Thick, chewy wheat noodles in a hot dashi broth, served with light, crispy shrimp and vegetable tempura.", "suggestedCookingTime": 20},
    {"name": "Unadon (Eel Bowl)", "category": "Main Courses", "cuisines": ["japanese", "fine dining"], "description": "Grilled freshwater eel glazed with a sweet soy-based sauce, served over a bed of steamed white rice.", "suggestedCookingTime": 20},
    {"name": "Shoyu Ramen", "category": "Main Courses", "cuisines": ["japanese", "ramen"], "description": "Tokyo-style ramen with a clear, soy-sauce flavored broth, curly noodles, bamboo shoots, and roasted pork.", "suggestedCookingTime": 15},
    {"name": "Okonomiyaki", "category": "Main Courses", "cuisines": ["japanese", "street food"], "description": "A savory Japanese cabbage pancake mixed with pork belly and seafood, topped with mayo, sweet sauce, and bonito.", "suggestedCookingTime": 20},
    {"name": "Spicy Tuna Roll", "category": "Main Courses", "cuisines": ["japanese", "sushi"], "description": "Sushi roll filled with minced tuna mixed with spicy mayo, wrapped in nori and rice.", "isSpicy": True, "isGlutenFree": True, "suggestedCookingTime": 10},
    {"name": "Sukiyaki", "category": "Main Courses", "cuisines": ["japanese", "fine dining"], "description": "Thinly sliced beef, tofu, and vegetables simmered right at your table in a sweet soy and mirin broth.", "suggestedCookingTime": 25},
    {"name": "Yakisoba", "category": "Main Courses", "cuisines": ["japanese", "street food", "izakaya"], "description": "Stir-fried wheat noodles with pork, cabbage, and carrots in a sweet and savory sauce.", "suggestedCookingTime": 15},
    {"name": "Salmon Teriyaki Bento", "category": "Main Courses", "cuisines": ["japanese", "teishoku"], "description": "A complete meal box featuring glazed salmon, rice, miso soup, salad, and a small side dish.", "suggestedCookingTime": 20},
    {"name": "Gyudon (Beef Bowl)", "category": "Main Courses", "cuisines": ["japanese", "teishoku"], "description": "Thinly sliced beef and onions simmered in a mildly sweet broth flavored with dashi, soy sauce, and mirin, over rice.", "suggestedCookingTime": 15},
    {"name": "Miso Black Cod", "category": "Main Courses", "cuisines": ["japanese", "fine dining"], "description": "A buttery fillet of black cod marinated for 48 hours in sweet saikyo miso, then broiled to perfection.", "isGlutenFree": True, "suggestedCookingTime": 20},
    {"name": "Dragon Roll", "category": "Main Courses", "cuisines": ["japanese", "sushi"], "description": "An inside-out sushi roll featuring shrimp tempura and cucumber, draped with thinly sliced avocado.", "suggestedCookingTime": 15},
    {"name": "Zaru Soba", "category": "Main Courses", "cuisines": ["japanese"], "description": "Chilled buckwheat noodles served on a bamboo tray with a soy-based dipping sauce, perfect for warm weather.", "isVegetarian": True, "suggestedCookingTime": 15},
    {"name": "Omurice", "category": "Main Courses", "cuisines": ["japanese", "cafe"], "description": "A fluffy, western-influenced Japanese omelette draped over ketchup-flavored chicken fried rice.", "suggestedCookingTime": 15},
    {"name": "Shabu Shabu", "category": "Main Courses", "cuisines": ["japanese", "fine dining"], "description": "A Japanese hot pot where diners swish paper-thin beef slices in a hot kombu broth, served with ponzu and sesame dips.", "isGlutenFree": True, "suggestedCookingTime": 30},
    {"name": "Katsu Curry", "category": "Main Courses", "cuisines": ["japanese", "teishoku"], "description": "A crispy breaded pork cutlet served with a rich, slightly sweet Japanese curry sauce over rice.", "suggestedCookingTime": 20},

    # Sides (10)
    {"name": "Gohan (Steamed Rice)", "category": "Sides", "cuisines": ["japanese", "sushi", "teishoku"], "description": "A bowl of premium short-grain Japanese white rice.", "isVegan": True, "isGlutenFree": True, "suggestedCookingTime": 20},
    {"name": "Tsukemono (Pickles)", "category": "Sides", "cuisines": ["japanese", "teishoku"], "description": "An assortment of traditional Japanese pickled vegetables, including daikon, plum, and cucumber.", "isVegan": True, "isGlutenFree": True, "suggestedCookingTime": 5},
    {"name": "Tamagoyaki", "category": "Sides", "cuisines": ["japanese", "sushi", "izakaya"], "description": "A slightly sweet, layered rolled omelette, cooked in a rectangular pan.", "isVegetarian": True, "isGlutenFree": True, "suggestedCookingTime": 10},
    {"name": "Natto", "category": "Sides", "cuisines": ["japanese", "breakfast"], "description": "Fermented soybeans with a distinct, strong flavor and sticky texture, served with mustard and soy sauce.", "isVegan": True, "isGlutenFree": True, "suggestedCookingTime": 5},
    {"name": "Onigiri", "category": "Sides", "cuisines": ["japanese", "street food"], "description": "A triangular rice ball wrapped in seaweed, filled with salted salmon or pickled plum.", "isGlutenFree": True, "suggestedCookingTime": 10},
    {"name": "Kinoko Butter Yaki", "category": "Sides", "cuisines": ["japanese", "izakaya"], "description": "A mix of Japanese mushrooms (shiitake, enoki, shimeji) sautéed in butter and soy sauce.", "isVegetarian": True, "isGlutenFree": True, "suggestedCookingTime": 10},
    {"name": "Korokke", "category": "Sides", "cuisines": ["japanese", "street food"], "description": "A Japanese potato croquette, breaded with panko and deep-fried, served with sweet tonkatsu sauce.", "suggestedCookingTime": 15},
    {"name": "Daikon Salad", "category": "Sides", "cuisines": ["japanese", "izakaya"], "description": "Crisp, julienned white radish salad with a light plum or sesame dressing.", "isVegan": True, "isGlutenFree": True, "suggestedCookingTime": 5},
    {"name": "Nasu Dengaku", "category": "Sides", "cuisines": ["japanese", "izakaya"], "description": "Broiled eggplant halves glazed with a sweet and savory caramelized miso paste.", "isVegan": True, "isGlutenFree": True, "suggestedCookingTime": 15},
    {"name": "Kinpira Gobo", "category": "Sides", "cuisines": ["japanese", "teishoku"], "description": "Julienned burdock root and carrots stir-fried and simmered in soy sauce, mirin, and sesame oil.", "isVegan": True, "isGlutenFree": True, "suggestedCookingTime": 15},

    # Desserts (10)
    {"name": "Matcha Ice Cream", "category": "Desserts", "cuisines": ["japanese", "cafe"], "description": "Rich, creamy ice cream flavored with premium bitter-sweet green tea powder.", "isVegetarian": True, "isGlutenFree": True, "suggestedCookingTime": 0},
    {"name": "Mochi Ice Cream", "category": "Desserts", "cuisines": ["japanese"], "description": "Bite-sized balls of ice cream enveloped in a soft, chewy, sweet rice dough.", "isVegetarian": True, "isGlutenFree": True, "suggestedCookingTime": 0},
    {"name": "Dorayaki", "category": "Desserts", "cuisines": ["japanese", "street food", "bakery"], "description": "A sweet red bean paste sandwich made of two fluffy, pancake-like patties.", "isVegetarian": True, "suggestedCookingTime": 5},
    {"name": "Taiyaki", "category": "Desserts", "cuisines": ["japanese", "street food", "bakery"], "description": "A warm, fish-shaped cake filled with sweet azuki bean paste or vanilla custard.", "isVegetarian": True, "suggestedCookingTime": 10},
    {"name": "Daifuku", "category": "Desserts", "cuisines": ["japanese", "bakery"], "description": "A soft, traditional glutinous rice confection stuffed with sweet red bean paste.", "isVegan": True, "isGlutenFree": True, "suggestedCookingTime": 0},
    {"name": "Purin", "category": "Desserts", "cuisines": ["japanese", "cafe"], "description": "A firm, smooth Japanese caramel custard pudding.", "isVegetarian": True, "isGlutenFree": True, "suggestedCookingTime": 0},
    {"name": "Mitarashi Dango", "category": "Desserts", "cuisines": ["japanese", "street food"], "description": "Chewy rice dumplings served on a skewer and glazed with a sweet soy syrup.", "isVegan": True, "isGlutenFree": True, "suggestedCookingTime": 10},
    {"name": "Yuzu Sorbet", "category": "Desserts", "cuisines": ["japanese", "fine dining"], "description": "A highly refreshing and tart palate cleanser made from the Japanese citrus fruit, yuzu.", "isVegan": True, "isGlutenFree": True, "suggestedCookingTime": 0},
    {"name": "Anmitsu", "category": "Desserts", "cuisines": ["japanese", "cafe"], "description": "A classic dessert bowl of agar jelly cubes, sweet red bean paste, fresh fruits, and black syrup.", "isVegan": True, "isGlutenFree": True, "suggestedCookingTime": 0},
    {"name": "Castella Cake", "category": "Desserts", "cuisines": ["japanese", "bakery"], "description": "A very fine, moist, and spongy honey cake originally from Nagasaki.", "isVegetarian": True, "suggestedCookingTime": 0}
]

def append_to_file():
    with open("src/lib/global-dish-library.ts", "a") as f:
        for dish in american_dishes + mexican_dishes + japanese_dishes:
            f.write(f"  {json.dumps(dish)},\n")

if __name__ == "__main__":
    append_to_file()
